Feat/메인페이지 파티모집프리뷰구현 어드민페이지지pr용 #1300
42organization/42gg.client pull request #1304
Opened 2024-03-15 06:58 UTC by mantoing

## 📌 개요 
  - 어드민 파티 페이지에 template, category, report, 부분을 구현하였고, 메인페이지에서 파티 미리보기 컴포넌트 추가하였습니다.

2024-03-15 07:46 UTC, contemplation-person requested changes

2024-03-15 07:46 UTC, contemplation-person commented on components/admin/party/PartyNav.tsx
> +  const [navValue, setNavValue] = useState('penalty');
usestate 말고 바로 onclick 하는게 더 좋아보임
함수로 빼서 정의하는거도 고려

2024-03-15 07:46 UTC, contemplation-person commented on components/admin/party/PartyReportNav.tsx
> +  const [navValue, setNavValue] = useState('noshow');
위랑동일

2024-03-15 07:46 UTC, contemplation-person commented on components/admin/party/PartyTemplate.tsx
> +    console.log('Render');
```suggestion
```

2024-03-15 09:09 UTC, mantoing commented on components/admin/party/PartyTemplate.tsx
> +    console.log('Render');
요거는 뺴면 린트에 걸리는데 렌더링할 방법이 없더라구요

2024-03-15 09:15 UTC, izone00 commented on styles/party/PartyMain.module.scss
- 이 파일은 PartyMain페이지 구현 scss라 다른 파일에 scss써야 될 것 같습니다.

2024-03-15 09:16 UTC, izone00 commented on types/partyTypes.ts
- 지워진거 복구해야 될것 같아요

2024-03-15 09:16 UTC, izone00 commented on types/modalTypes.ts
> +  | `TOURNAMENT-${TournamentModal}`;
- 지워진거 복구해야 될것 같아요

2024-03-15 09:16 UTC, mantoing commented on styles/party/PartyMain.module.scss
근데 이미 있는 styles에서만 사용하는것인데 오하려 새로 만들어서 관리하는게 더 복잡하지않을까요?

2024-03-15 09:17 UTC, mantoing commented on types/modalTypes.ts
> +  | `TOURNAMENT-${TournamentModal}`;
어 저가 사용하지않아서 지운건데 복구해야하나요 ?

2024-03-15 09:19 UTC, mantoing commented on types/partyTypes.ts
우정님이 만들고 있으신거 머지하면 어차피 바뀌는 부분이라 일부러 전으로 돌린건데 다시 복구해야하나요 ?

2024-03-15 09:19 UTC, izone00 commented on components/main/PartyPreview.tsx
> +  console.log(partyRooms);
- 지워야 할 것 같아요

2024-03-15 09:19 UTC, izone00 commented on components/main/PartyPreview.tsx
> +  const limitedRooms = partyRooms.slice(0, 3);
- 이거 파티가 3개 미만으로 있어도 작동 하나요?

2024-03-15 09:21 UTC, mantoing commented on components/main/PartyPreview.tsx
> +  const limitedRooms = partyRooms.slice(0, 3);
3개 미만으로 있으면 2개까지만 생겼던걸로 기억합니다.

2024-03-15 09:23 UTC, izone00 commented on components/admin/party/PartyTemplate.tsx
> +    console.log('Render');
- 어떤게 렌더링이 안되는 건가요?

2024-03-15 09:26 UTC, mantoing commented on components/admin/party/PartyTemplate.tsx
> +    console.log('Render');
그 수정이나 삭제되었을때 직후에 렌더링이 되어야하는데 렌더링 처리가 커스텀훅에서 처리가 안되서 useEffect로 재 렌더링 시켜주는건데 다른 방법이 있을까요 ?

2024-03-15 09:28 UTC, izone00 commented on components/admin/party/PartyTemplate.tsx
> +      <div className={styles.userManagementWrap}>
- userManagementWrap은 안맞는것 같아요

2024-03-15 09:28 UTC, izone00 commented on components/admin/party/PartyTemplate.tsx
- 안쓰는 className 다 바꿔야될것 같아요

2024-03-15 09:28 UTC, izone00 commented on components/admin/party/PartyCategory.tsx
- 안쓰는 className 다 바꿔야될것 같아요

2024-03-15 09:29 UTC, izone00 commented on components/admin/party/PartyCategory.tsx
> +  const deletehandler = (categoryId: number) => {
- 이 함수는 없어도 동일할 거 같아요

2024-03-15 09:30 UTC, izone00 commented on components/admin/party/PartyCategory.tsx
> +      createCategory(newCategoryName);
- 카테고리 만들고 newCategoryName = ''로 자동으로 초기화가 되나요? 안되면 해주면 좋을거 같아요

2024-03-15 09:31 UTC, izone00 commented on components/admin/party/AdminPartyReport.tsx
- 이 파일이랑 PartyReportNav랑 하나만 써도 좋을 거 같아요

2024-03-15 09:33 UTC, izone00 commented on components/modal/Party/TemplateModal.tsx
> +      <div className={styles['modal-overlay']}>
- className을 여기서만 CamelCase를 안쓴 이유가 있나요?

2024-03-15 09:34 UTC, mantoing commented on components/admin/party/PartyTemplate.tsx
이게 안쓰는 classname이 아니고 디폴트값으로 common.scss에 있는 스타일을 참조합니다.

2024-03-15 09:34 UTC, izone00 requested changes
- 지금 admin에 있는 className들이 불필요한게 너무 많아서 정리하면 좋을거 같아요

2024-03-15 09:36 UTC, izone00 commented on components/admin/party/PartyTemplate.tsx
> +    console.log('Render');
아하 그러네요 
이건 모달문제여서 일단은 그냥 두고 같이 생각해봐야 될 것같아요

2024-03-15 09:37 UTC, izone00 commented on styles/party/PartyMain.module.scss
이미 있는 styles가 아니고 제가 mainPage 스타일링 하고 있는 파일에
admin관련 scss를 넣은거라 합쳐도 의미가 없어요

2024-03-15 09:40 UTC, izone00 commented on types/partyTypes.ts
이게 이미 만들어서 커밋된걸 지운거라서 이상태로 올리면 지운걸로 가져다써야되서 힘들것같아요
올릴때 작성하신것만 올려주시면 될 것 같아요

2024-03-15 09:41 UTC, izone00 commented on types/modalTypes.ts
> +  | `TOURNAMENT-${TournamentModal}`;
근데 이게 재윤님이 쓰는것때매 작성된게 아니고 party페이지 모달때매 들어있는거라  지우면 안될 것 같아요

2024-03-15 09:43 UTC, izone00 commented on components/admin/party/PartyTemplate.tsx
import styles from 'styles/party/PartyMain.module.scss';

styles가 여기서 import되는데 여기 없는 className을 common에 있는걸로 자동으로 가져오나요?

2024-03-15 09:58 UTC, mantoing commented on components/admin/party/PartyTemplate.tsx
> +    console.log('Render');
그럼 일단 머지하고 나중에 고치도록 하겠습니다.

2024-03-16 08:32 UTC, izone00 commented on hooks/party/usePartyRoomList.tsx
이 파일은 사용이 안되는것 같은데 어디서 사용하나요?

2024-03-16 08:42 UTC, izone00 reviewed
아래 코드에서 보이는 대부분의 className이 안쓰이는것 같아요
안쓰이는 className만 지우면 될 것 같아요
```
<TableContainer className={styles.tableContainer} component={Paper}>
        <Table className={styles.table} aria-label='UserManagementTable'>
          <AdminTableHead tableName={'partyCategory'} table={tableTitle} />
          <TableBody className={styles.tableBody}>
            {categories.map((c) => (
              <TableRow key={c.categoryId} className={styles.tableRow}>
                {tableFormat['partyCategory'].columns.map((columnName) => {
                  return (
                    <TableCell
```

2024-03-16 09:05 UTC, izone00 approved these changes

2024-03-17 04:10 UTC, izone00 approved these changes

2024-03-17 11:42 UTC, contemplation-person approved these changes

2024-03-17 11:44 UTC, merged