[Fix] 프리뷰 선택시 navigate설정, 배경이미지 추가
42organization/42gg.client pull request #1325
Opened 2024-03-25 07:17 UTC by mantoing

## 📌 개요 
  - 메인페이지 파티 프리뷰 부분에 클릭시 해당 각 방으로 navigate되게 구현하였습니다.
  - 메인페이지 프리뷰의 background img를 추가하였습니다.

2024-03-25 12:51 UTC, contemplation-person commented on components/main/PartyPreview.tsx
> +    console.log(roomId);
```suggestion
```

2024-03-25 12:51 UTC, contemplation-person reviewed
필요없는 콘솔로그 항상 지워줄 것.

2024-03-25 12:52 UTC, contemplation-person requested changes
필요없는 콘솔로그 지워줄것.

2024-03-26 05:58 UTC, izone00 approved these changes

2024-03-26 11:09 UTC, merged