[Feat] room을 동적 라우팅에서 쿼리문으로 라우팅 변환 1384
42organization/42gg.client pull request #1385
Opened 2024-04-11 15:30 UTC by contemplation-person

## 📌 개요 
  - aws 이유로 동적 라우팅 방식에서 쿼리 방식으로 변경
 ## 💻 작업사항 
  -  /party/[roomId] -> /party/room?id=[id] 로 변경

2024-04-12 08:17 UTC, yoouyeon requested changes
pr 보니까 수정한 내용을 테스트 배포 브랜치에 merge하고 있는데, 이 브랜치를 기준으로 최신화하게 되면 나중에 6기 작업들 main으로 머지할 때 테섭 배포되어 있는 모집 기능 작업까지 함께 머지될 것 같아서요.

나중에 브랜치 전략을 다시 한번 얘기해봐야 할 것 같긴 한데, 지금 상황에서는 아래 그림처럼 수정사항들은 6기 개발 브랜치에 계속 올리고, 정기적으로 테스트 배포를 하는 식으로 생각을 하고 있었는데, 6기 분들 사이에서는 어떻게 얘기되었는지 궁금합니다.

![image](https://github.com/42organization/42gg.client/assets/57761286/0cbc1de2-85bb-46e9-93b9-7ee848e660ae)

2024-04-12 09:16 UTC, contemplation-person commented
저희는 윗 기수 분들이 작업하는 팀원 모집 기능이랑 같이 올라가는 것으로 인지하고 있었어요. (BE쪽에서 같이 올라간다고 해서)
그래서 테스트에 머지하고 테스트가 메인에 머지되는 방향으로 인지하고 있었습니다.

2024-04-12 11:15 UTC, yoouyeon commented
@contemplation-person 아하 그랬군요...! 사실 저는 따로 올라갈 수도 있다고 알고 있었어서 이부분은 다시 확인하고 알려드릴게요!
BE에서는 같이 배포하기로 했다고 했으니 아마 같이 올라갈 가능성이 높을 것 같은데 맞다면 이번에는 이미 작업하신 내용도 있고 하니 지금 방식처럼 해도 괜찮을 것 같습니다.
지금 상황과는 별개로 지금 브랜치 전략이 좀 복잡하고 헷갈리는것도 맞는 것 같아서 이번 작업 끝나면 이 부분도 좀 손봐야 할 것 같긴 하네요 ㅎㅎ
알려주셔서 감사합니다!

2024-04-13 20:45 UTC, mantoing approved these changes

2024-04-15 05:31 UTC, greatSweetMango approved these changes

2024-04-16 04:06 UTC, merged