[Feat] profile layout #1446
42organization/42gg.client pull request #1467
Opened 2024-07-31 05:01 UTC by JeongRon

## 📌 개요 
  - profile page UI 제작
 ## 💻 작업사항 
  - 컴포넌트 제작
      1. AgendaUserSearchBar : 유저 검색 UI
      2. ProfileImageCard : 유저 이미지가 들어가 포함된 카드 UI 
      3. ProfileContent : 유저 소개 텍스트, acheivements 포함된 UI
      4. ParticipatingTeam : 참여중인 팀 컨테이너 UI 
      5. ParticipatingAgendaItem : 참여중인 팀 안의 아젠다 정보(팀이름, 아젠다 이름) UI
      6. AgendaHistory : 아젠다 기록 컨테이너 UI
      7. HistoryItem : 아젠다 기록 안의 아젠다 정보 UI 
 
##💡관련 Issue
- #1446

2024-07-31 05:06 UTC, JeongRon commented
아직 전반적으로 많이 부족하지만, PR올렸습니다! 나중에 작업 할때 개선하면 좋을 것들 리뷰 부탁드려요!

2024-08-01 01:23 UTC, siwolee commented
Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="/styles/reset.css"). Use Document instead. 
See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component

이건 다른 부분이긴 한데 혹시 수정해서 같이 올려주실 수 있을까요?
app.tsx에  reset css 들어간 부분입니다.

2024-08-01 01:23 UTC, siwolee requested changes

2024-08-01 01:23 UTC, siwolee commented on styles/agenda/Profile/AgendaProfile.module.scss
> +}
@include  container해서 기본 border랑 radius 바로 가져와주심 좋을것같아요

2024-08-01 03:29 UTC, irenee-14 approved these changes
UI적인 부분이 많아서 급한 API 부터 해결해도 될 것 같습니당,,,,,

2024-08-01 03:29 UTC, irenee-14 commented on components/agenda/Profile/HistoryItem.tsx
> +          />
image를 컴포넌트식으로 불러서 사용했으면 좋겠습니다! 
```
import Time from '/image/agenda/Time.svg';
<Time
            width={15}
            height={15}
            alt='Time'
            className={styles.imageBox}
          />
```
이런식으로 사용하면 될 것 같아요~

2024-08-01 03:29 UTC, irenee-14 commented on components/agenda/Profile/HistoryItem.tsx
> +        />
여기도 이미지 형식을 바꿨으면 좋겠어요!

2024-08-01 03:29 UTC, irenee-14 commented on components/agenda/Profile/ParticipatingTeam.tsx
> +const ParticipatingTeam = () => {
프로필 화면에서 `참여중인 팀`과 `아젠다 기록` 부분이 위의 프로필과 설명 부분의 UI와 약간 동떨어져 보입니다! UI 부분이니 이후에 비슷한 느낌으로 폰트 크기와 색상 등 변경부탁드립니다.

2024-08-01 03:29 UTC, irenee-14 commented on components/agenda/Profile/ParticipatingTeam.tsx
> +        <ParticipatingAgendaItem />
각 item 양 옆 margin이 너무 넓은 것 같아요! 위아래 gap과 비율이 맞았으면 좋겠습니다!

2024-08-01 03:29 UTC, irenee-14 commented on components/agenda/Profile/ProfileContent.tsx
> +              className={styles.imageBox}
image 형식!

2024-08-01 03:29 UTC, irenee-14 commented on components/agenda/Profile/ProfileImageCard.tsx
> +            className={styles.imageBox}
image!

2024-08-01 03:29 UTC, irenee-14 commented on pages/agenda/profile/index.tsx
> +        </div>
<div className={styles.agendaUserSearchBarWrap}>
하나의 요소만 들어가면 <AgendaUserSearchBar /> 내부로 div를 빼도 될 것 같아요!

2024-08-01 05:09 UTC, siwolee approved these changes
api 우선 진행하는 부분에 동의했습니다

2024-08-01 05:10 UTC, merged