[Feat] team page api #1474
42organization/42gg.client pull request #1487
Opened 2024-08-19 05:03 UTC by JeongRon

## 📌 개요 
  - 팀 페이지 API 연결
 ## 💻 작업사항 
  - 
 ## ✅ 변경로직 
  -

2024-08-19 07:02 UTC, irenee-14 commented on pages/agenda/[agendaKey]/[teamUID]/index.tsx
> +    }
이렇게 변환하는 부분은 다른 곳에서도 쓰일 경우를 위해 함수로 빼도 좋을 것 같아요! 일단 저...

2024-08-19 07:14 UTC, siwolee commented on components/agenda/teamDetail/TeamButtons.tsx
> +          }
동의합니다

2024-08-19 07:20 UTC, siwolee commented on pages/agenda/[agendaKey]/[teamUID]/index.tsx
> +    switch (data.teamLocation) {
이건 이런 식으로 해도 깔끔할 것 같아여
```suggestion
const locations={
    '서울': 'SEOUL', ...
   }
const teamLocation = locations[data.teamLocation]; 
```

2024-08-19 07:28 UTC, siwolee requested changes
저는 다른 부분은 괜찮은 것 같고, checkModal 부분만 모달제작하신 의도에 맞춰서 수정해주시면 OK입니다. 고생하셨습니다.

2024-08-20 03:23 UTC, siwolee approved these changes
LGTM~

2024-08-20 03:27 UTC, irenee-14 approved these changes
수정된 부분 확인했습니다~~

2024-08-20 04:45 UTC, merged