[Feat]Navbar #1493
42organization/42gg.client pull request #1499
Opened 2024-08-21 11:57 UTC by siwolee

## 📌 개요 
  - Navbar 및 헤더 적용
 
 ## 💻 작업사항 
  - 디자인 픽스
  - Navbar 애니메이션 및 효과
  - 배경, 로고 등 변경

https://github.com/user-attachments/assets/17b7abbe-b48d-4f1d-8020-495da9a59559

2024-08-21 12:08 UTC, JeongRon approved these changes
Wow LGTM! 👍

2024-08-22 06:54 UTC, irenee-14 requested changes
헤더가 명확하게 구분이 생기면서 헤더에 body 부분이 너무 가깝게 붙어있는 것 같습니다! 이 부분도,, 수정 부탁,,,,

2024-08-22 06:54 UTC, irenee-14 commented on Layout/LayoutProvider.tsx
> +  console.log(app);
console.log~

2024-08-22 06:54 UTC, irenee-14 commented on Layout/LayoutProvider.tsx
> +    case '':
이 부분의 역할은 무엇인가요?! default 부분과 다른건가요?

2024-08-22 06:54 UTC, irenee-14 commented on components/agenda/modal/AgendaModalProvider.tsx
> +        >
오잉 이부분 merge 된 줄 알았는데 왜 또 있을까요...?

2024-08-22 06:54 UTC, irenee-14 commented on components/agenda/modal/ModifyModal.tsx
이 파일도 왜 여기있을까요....?

2024-08-22 06:54 UTC, irenee-14 commented on components/agenda/Layout/MenuBarContent.tsx
> +      <button onClick={moveTo(href)} className={styles.button}>
여기 메뉴 바 항목 가까이 가면 text가 움직이는거 너무 좋아요!!

2024-08-23 08:06 UTC, siwolee commented on Layout/LayoutProvider.tsx
> +    case '':
pathname 없을 경우 : 인덱스 페이지입니다.
해당 페이지 레이아웃을 아젠다 레이아웃으로 함께 넘겼습니다!
이렇게 쓸 경우 첫 케이스에서 걸렸을 때부터 실행이 들어갔지만 break이나 return문이 없어 다음 케이스로 넘어가기 때문에, 두 케이스에서 같은 값을 리턴하게 됩니다.

2024-08-23 08:07 UTC, siwolee commented on components/agenda/modal/AgendaModalProvider.tsx
> +        >
제가 아젠다 브랜치 통합 안됀 상태에서 올린거같아요;;

2024-08-23 08:08 UTC, siwolee commented on components/agenda/modal/ModifyModal.tsx
동일한 문제...

2024-08-23 10:29 UTC, siwolee commented
수정해서 올려두었습니다!

2024-08-26 03:33 UTC, irenee-14 approved these changes
수정사항 확인 했습니다~~ LGTM~~

2024-08-26 03:34 UTC, merged