[Style] CSS 스타일 개선
42organization/42gg.client pull request #1571
Opened 2024-10-05 04:38 UTC by JeongRon

## 📌 개요 
  - CSS 스타일 개선
 ## 💻 작업사항 
- **개행 처리 기능 추가 / 대회 설명, 공지사항 내용 작성 -> 개행 처리 안되어 있는 것 개선**
  <img width="800" alt="스크린샷 2024-10-05 오후 1 28 06" src="https://github.com/user-attachments/assets/0bcbc7e5-7d73-4d65-a066-a5660d0a3455">
  <img width="800" alt="스크린샷 2024-10-05 오후 1 28 54" src="https://github.com/user-attachments/assets/250aa53f-5889-477c-ae8a-d0ddb73b2904">

- **index 첫 페이지 / 버튼 클릭 모션 개선, 모집 중 아젠다 없을 시 UI 개선**
  <img width="800" alt="스크린샷 2024-10-05 오후 1 25 29" src="https://github.com/user-attachments/assets/331a7562-4d8c-4376-9ee1-f88973bb6d83">

- **프로필 페이지 / 아젠다 프로필 카드 개선 (업적 설명 마우스 hover처리)**
  <img width="400" alt="스크린샷 2024-10-05 오후 1 30 11" src="https://github.com/user-attachments/assets/ec6ba2f7-d4d2-44ef-a3fb-f3203a28ecf7">

- **프로필 페이지 / 아젠다 리스트 UI 개선 (내 프로필 아닐 시- 참여중 안보이게 개선, 리스트 없을 시 텍스트 추가)** 
  <img width="800" alt="스크린샷 2024-10-05 오후 1 36 36" src="https://github.com/user-attachments/assets/6cb610bc-b4f7-4e42-84d3-b8d000254526">
 <img width="800" alt="스크린샷 2024-10-05 오후 1 36 39" src="https://github.com/user-attachments/assets/3cafcd23-2c20-429b-a78c-296e13b950de">

2024-10-06 04:54 UTC, irenee-14 requested changes
굳굳 호버되는 부분이 아주 좋네요! 머지 안된 부분만 확인 부탁드려요~

2024-10-06 04:54 UTC, irenee-14 commented on pages/agenda/index.tsx
> +            {'|'}
기존 deploy된 부분이 merge가 안 된것 같습니다! 확인부탁드려요~

2024-10-06 04:54 UTC, irenee-14 commented on pages/agenda/profile/user.tsx
> +                  },
이부분은 클래스로 빼면 적용이 안되나요?! 가능하다면 부탁드립니다!

2024-10-06 04:54 UTC, irenee-14 commented on styles/agenda/agendaDetail/tabs/AnnouncementItem.module.scss
>  .announcementContent {
공지사항 부분도 개행 처리가 된건가요?!

2024-10-07 01:10 UTC, JeongRon commented on pages/agenda/profile/user.tsx
> +                  },
이 부분은 mui 코드여서 클래스로 따로 빼서 처리가 안되는 것으로 알고 있어요 😅

2024-10-07 08:31 UTC, irenee-14 approved these changes

2024-10-07 10:21 UTC, siwolee commented on components/agenda/Profile/HistoryList.tsx
> +          </div>
멘트 사소하지만 좋네여...

2024-10-07 10:23 UTC, siwolee approved these changes
LGTM..

2024-10-07 10:23 UTC, siwolee commented on components/agenda/agendaDetail/tabs/AgendaDescription.tsx
> +            <span className={styles.preWrap}>{agendaContent}</span>
굿굿

2024-10-07 10:23 UTC, merged