Feat/관리자용 모달 구현#622
42organization/42gg.client pull request #630
Opened 2023-02-01 07:36 UTC by Wilbur0306

## 📌 개요  
  - admin page에서 사용할 (대상이 "전체"인) notification modal
  - admin page에서 사용할  penalty modal
 ## 💻 작업사항 
  -  ### **penalty modal**
  1. 패널티를 부여할 시간(시, 분) 작성하는 입력창 생성하였습니다.
  2. mock api를 만들어서 시험해본 결과 정상적으로 전달되는 것을 확인할 수 있었습니다.
  3. 지금은 보이지 않지만 추후에 하단에 "남은 시간"이라는 항목을 만들어서 부여된 패널티 시간이 끝날 때까지 남은 시간이 얼마인지 알 수 있게끔 표시할 계획입니다.

- ### **notification modal**
 1. 42gg 사용자 전체를 대상으로 noti를 전달하는 입력창을 생성하였습니다.

## ❔질문
- notification modal에서 입력창에 장문의 글을 작성하면 자동으로 개행이 되지 않고 쭉 이어서 적히는 것을 확인하실 수 있습니다. CSS을 활용하여 어떻게 해결해야할지 모르겠습니다.

2023-02-01 07:40 UTC, 42sungwook commented
모달을 띄우려면 띄우는 곳에서
  
`const setModal = useSetRecoilState(modalState);`
선언을 하고
버튼 안에
`onClick={()=>setModal({ modalName: 'ADMIN-PROFILE', intraId:"daijeong"})}`
이런 형태로 코드를 넣어주시면 됩니다
추가된 modalName 은
ADMIN-PROFILE
ADMIN-PENALTY
ADMIN-NOTI_ALL
이렇게 세가지에요!

2023-02-01 09:37 UTC, mike2ox reviewed
코멘트 달게 좀 있어서 리뷰를 여기서 끊고 추가 작성하겠습니다.

PR 남기는 방식
- 팀원들이 PR로 올라온 코드를 실행 시키기 위해 어떤 작업을 해야하는지 작성할 것
- merge용도가 아닌 진행중인 코드지만 리뷰를 원하는 경우 PR 본문에 현재 어디까지 진행됐는지를 알려주거나 관련 issue를 달아주기
- **꼭 git pull해서 PR 본문에 적혀있는 내용을 확인 후에 코드 리뷰를 진행하기**

2023-02-01 09:37 UTC, mike2ox commented on components/modal/ModalProvider.tsx
> +import AdminNotiAllModal from './admin/adminNotiAllModal';
component를 표현하는 tsx파일이면 component naming rule을 file name에도 적용해주는게 좋습니다
참고 : https://ko.reactjs.org/docs/jsx-in-depth.html

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminNotiAllModal.tsx
> +  const [allNoti, setAllNoti] = useState<any>();
타입은 any로 하더라도 초기값은 되도록 비워두지 않는게 좋아요.
막상 렌더링단계에서 정상처리 되도 에러가 발생할 수 있거든요.

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminNotiAllModal.tsx
> +      `http://localhost:3000/api/admin/users/intraId/penalty`
notification관련 modal 파일인데 url은 penalty로 되어있습니다.

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminNotiAllModal.tsx
> +      editedAllNoti.notification = '';
react의 관리대상(hook을 통한 state)이면 setState를 이용해서 값을 변경해주시는게 좋습니다.

참고 : [state 변경에 setState를 써야하는 이유](https://velog.io/@codns1223/React-state-%EB%B3%80%EA%B2%BD%EC%8B%9C-setState%EB%A1%9C-%EB%B3%80%EA%B2%BD%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0)

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminNotiAllModal.tsx
> +    if (errMsg) alert(errMsg);
alert이 아니라 모달의 하단부(확인-취소 버튼 위에)에 errMsg가 나타나는 방식 적용해보세요.
그러면 유저입장에서 데이터를 잘못 입력했을 때 경고창을 클릭해야만 이후 과정을 진행할 수 있는 불필요한 경험이 없어집니다.

참고 : https://forum.radzen.com/uploads/default/original/2X/5/5c60c4b36c88ae47d8179f4d3d69302b0f679ead.png

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminNotiAllModal.tsx
> +  const cancelEditHandler = () => setModal({ modalName: null });
변수 선언은 왠만하면 해당 함수 초입부에 해주시는걸 권장합니다.
(ex. recoil state 가져오기)

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminNotiAllModal.tsx
> +      `http://localhost:3000/api/admin/users/intraId/penalty`
그리고 adminNotiAllModal같은 경우 사전에 백엔드에서 data를 가져오는게 아닌
일방적으로 관리자가 기입하면 Post하는 거로 규정한거 같은데 맞을까요?

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminNotiAllModal.tsx
> +            value={allNoti?.notification}
input tag의 value가 undefined일 때 발생하는 에러가 있습니다.

<img width="441" alt="스크린샷 2023-02-01 오후 6 17 14" src="https://user-images.githubusercontent.com/22931103/216001638-30353539-aeff-49de-bd04-cdce13e433b7.png">

동일한 에러가 이번에 올려주신 modal들 전체( input tag를 사용하고 있는 )에서 발생하는게 확인되었습니다.
해당 이슈 한번 해결해 보시면 좋을거 같습니다.

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminPenaltyModal.tsx
> +          </button>
패널티를 보내고 나서 적용 버튼 하나만 사라지네요.
의도하신거 같긴한데 어떤 의도이신지 궁금합니다

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminNotiAllModal.tsx
> +          </button>
전체 알림을 보내고 modal에서 적용 버튼 하나만 사라지네요.
css 적용하신걸 보니 의도하신거 같긴한데 어떤 의도이신지 궁금합니다

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminPenaltyModal.tsx
> +  penaltyMinute: number | string;
시, 분으로 number 타입 하나로 표현이 가능합니다.
전달되는게 string이라서 `|`를 붙여주신거라면 parseInt함수를 사용해 penaltyHour, penaltyMinute의 타입을 int(number)로 통일하는게 어떨까 싶습니다.

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminPenaltyModal.tsx
> +  const [userPenalty, setUserPenalty] = useState<any>();
타입 정의하는게 당장은 어렵더라도 아래에 있는 editedPenalty 처럼 state의 초기값은 왠만하면 적어주시는게 좋습니다.

2023-02-01 09:37 UTC, mike2ox commented on components/modal/admin/adminPenaltyModal.tsx
> +  };
해당 handler 함수의 input parameter 구조와 type이 두가지 방식으로 오게된 이유가 궁금합니다.

2023-02-01 10:08 UTC, mike2ox commented on components/modal/admin/adminProfileModal.tsx
> +                    checked={userInfo?.racket_type === racket.id}
저희 code convention은 camelCase로 진행하기에 백에서 snake_case로 보내주면 1차로 camelCase로 변경 요청, 2차로 프론트에서 `camelCase : snake_case`로 받을 수 있도록 해주세요

2023-02-02 02:43 UTC, Wilbur0306 commented on components/modal/admin/adminPenaltyModal.tsx
> +          </button>
패널티 부여 시간을 작성하고 "적용" 버튼을 누르면 [적용] 버튼만 사라지면서 동시에 입력창에 있는 숫자가 고정되며 수정이 불가능하게 됩니다. 전체 회의에서 "수정"이라는 절차가 있으면 너무 번거로워져서, 수정해야되는 상황이 생기면 기존에 있던 패널티를 삭제하고 새로 생성하는 로직으로 하기로 결정이 되었습니다. 그래서 패널티 생성([적용] 버튼을 눌렀을 때)과 동시에 수정이 불가능하게 되는 식으로 구현하였습니다.

2023-02-02 02:49 UTC, Wilbur0306 commented on components/modal/admin/adminNotiAllModal.tsx
> +          </button>
패널티 수정을 처리한 방식과 마찬가지로, 전체 알림 부분 역시 수정을 대신하여 기존 것을 삭제하고 새로 생성하는 로직으로 구현하였습니다.

2023-02-02 05:56 UTC, mike2ox commented on components/modal/admin/adminPenaltyModal.tsx
> +          </button>
> 패널티 부여 시간을 작성하고 "적용" 버튼을 누르면 [적용] 버튼만 사라지면서 동시에 입력창에 있는 숫자가 고정되며 수정이 불가능하게 됩니다. 
<img width="221" alt="스크린샷 2023-02-02 오후 2 14 46" src="https://user-images.githubusercontent.com/22931103/216237641-e58bab23-58da-4a9a-8bec-d634af80c1da.png">
- 적용 클릭시 입력창에 있는 숫자가 변경되지 않기를 희망한다면 focus를 할 수 없도록 해주시면 좋을거 같아요. 
- 현재는 이미지처럼 focus가 되네요.

> 전체 회의에서 "수정"이라는 절차가 있으면 너무 번거로워져서, 수정해야되는 상황이 생기면 기존에 있던 패널티를 삭제하고 새로 생성하는 로직으로 하기로 결정이 되었습니다. 그래서 패널티 생성([적용] 버튼을 눌렀을 때)과 동시에 수정이 불가능하게 되는 식으로 구현하였습니다.
- 이 부분에 대해서는 @42sungwook 님 통해서 상세 내용을 들었습니다.
- 기획안을 기준으로 구현하시면서 최대한 UX적으로 편하게 만들어주시면 될거 같습니다!

2023-02-02 06:29 UTC, Wilbur0306 commented on components/modal/admin/adminNotiAllModal.tsx
> +  const cancelEditHandler = () => setModal({ modalName: null });
수정하였습니다!

2023-02-02 07:14 UTC, Wilbur0306 commented on components/modal/admin/adminNotiAllModal.tsx
> +            value={allNoti?.notification}
수정하였습니다! paresInt 함수를 사용하긴 했는데, 알맞은 방식으로 사용한건지 확신이 없어서 확인 해주시면 좋겠습니다.

2023-02-02 07:37 UTC, 42sungwook commented on components/modal/admin/adminProfileModal.tsx
> +                    checked={userInfo?.racket_type === racket.id}
이 부분은 노션 api명세를 토대로 작성했던거여서 노션 명세도 수정했습니다

2023-02-02 08:06 UTC, 42sungwook commented on components/modal/admin/adminPenaltyModal.tsx
> +  };
input 태그마다 다른 정보를 담고 있는데 이를 처리하는 handler를 하나로 합치기 위해서 name으로 구분을 주었습니다

2023-02-02 09:47 UTC, mike2ox commented on components/modal/admin/adminNotiAllModal.tsx
> +            value={allNoti?.notification}
넵 알겠습니다.
리뷰에 따른 수정사항 커밋은 수시로 push해주시면 확인해드릴게요

2023-02-02 09:51 UTC, mike2ox commented on components/modal/admin/adminPenaltyModal.tsx
> +  };
위에 있는 input parameter의 구조가 익숙하지 않아서 onChange를 다룰 때 자주 쓰이는 구조인지는 제가 파악해볼게요.

2023-02-02 10:55 UTC, Wilbur0306 commented on components/modal/admin/adminPenaltyModal.tsx
> +          </button>
focusing이 되지 않도록 <input readOnly>로 수정하였습니다!

2023-02-02 10:57 UTC, Wilbur0306 commented on components/modal/admin/adminPenaltyModal.tsx
> +  penaltyMinute: number | string;
수정하였습니다! paresInt 함수를 사용하긴 했는데, 알맞은 방식으로 사용한건지 확신이 없어서 확인 해주시면 좋겠습니다.

2023-02-02 10:57 UTC, Wilbur0306 commented on components/modal/admin/adminNotiAllModal.tsx
> +            value={allNoti?.notification}
제가 다른 곳에 답글로 달아야했던 것을 실수로 이 comment에 달았네요! 다시 수정하도록 하겠습니다

2023-02-09 02:43 UTC, m0song requested changes
요청드린 2개만 확인, 수정해주시면 제쪽에서 테스트할 때 문제없을거 같아요

2023-02-09 02:43 UTC, m0song commented on hooks/useUploadImg.ts
> +import imageCompression from 'browser-image-compression';
이거를 사용하기 위한 package가 package.json에 없네요.
확인해주시면 좋을거 같아요.

2023-02-09 02:43 UTC, m0song commented on components/modal/admin/adminFeedbackCheckModal.tsx
> +        await instance.post(`/pingpong/feedback/${props.id}/reminder`);
저희 url이 /pingpong/admin/ ~~ 로 바뀌었을텐데 admin이 아닌 pingpong 서비스 APi로 요청가는거지 않나요?

2023-02-09 02:50 UTC, mike2ox requested changes

2023-02-09 03:06 UTC, 42sungwook commented on components/modal/admin/adminFeedbackCheckModal.tsx
> +        await instance.post(`/pingpong/feedback/${props.id}/reminder`);
수정 했습니다! id를 body에 넣고 post 요청을 보내야하는거 같은데 이 부분은 이슈로 남겨놓을게요

2023-02-09 03:06 UTC, 42sungwook commented on hooks/useUploadImg.ts
> +import imageCompression from 'browser-image-compression';
추가했습니다!

2023-02-09 03:41 UTC, closed without merging

2023-02-09 04:08 UTC, mike2ox commented
일단 작업이 너무 길어져서 pr은 닫았습니다.
리뷰가 필요하면 reopen해서 어떤 부분에서 리뷰 받으면 좋을지 써주시면 되겠습니다.