[Feat] make notification page
42organization/42gg.client pull request #640
Opened 2023-02-07 02:20 UTC by mike2ox

## 📌 개요 
  - notification page 내부 contents 제작
 ## 💻 작업사항 
  - notification page에서 사용할 search bar, table, pagination, create button을 업로드 합니다
 
## 사전 작업
1. env.development가 일부 수정됐습니다. 
`NEXT_PUBLIC_ADMIN_MOCK_ENDPOINT 추가` 
2. 패키지 추가 및 업데이트 반영, 실행
```
npm i & npm run dev
```
3. 주소 입력 
`http://localhost:3000/admin/notification` ([참고](https://github.com/42organization/42gg.client/commit/7d34588c926906c04e245f2865bcf3221c62960e))

 ## 관련이슈
- #627 

## 질의
- 현재 SearchBar에 initSearch라는 함수를 전달하는 방식으로 기존 SearchBar을 그대로 쓰고 있는데 코드를 copy&paste해서 admin용으로 새로 분리를 하는게 맞을지 의문입니다.
- 실제 반응과 유사하게 mock api에 405(사용불가 http method)와 401(권한 X)을 계속 붙일까 고민 중입니다

2023-02-07 10:55 UTC, 42sungwook commented
전체 조회에 메시지는 안보이는데 의도된건지 궁금해요!

2023-02-07 23:30 UTC, mike2ox commented
코드에 추가보단 type -> message로 바꿔줘야할 거 같은데 hyunkle님하고 얘기 나눌게 하나 있어서 그때 수정할게요

2023-02-08 05:21 UTC, mike2ox commented
## 변경 사항
- 기존 inline되어있던 style을 scss파일로 분리했습니다(pagination, table, button)
- message column이 빠져있어서 추가했습니다.
- mock data 업데이트 (random 사용)

## 고민
- pagination이나 검색을 사용하면 table width가 flex하게 바뀌는거를 확인할 수 있습니다. page내 contents들의 사이즈가 고민입니다.
- 마지막으로 확정한건 notification page에서 announce 타입만 만들 수 있도록 확정해놔서 생성된 notification들을 불러올때도 announce 타입만 오는건지 확인 필요(BE 담당자와 talk)

2023-02-08 06:18 UTC, raehy19 requested changes
정말 정말 수고 많으셨습니다 !!! 여러 컴포넌트에 적용할 수 있게 고민하시면서 이렇게 잘 만들어주셔서 관리자 페이지 남은 것들은  금방 끝날 수 있을 것 같네요  사소한 코멘트 한번 확인해주시면 될것같습니다 ~~ :)

2023-02-08 06:18 UTC, raehy19 commented on components/admin/notification/NotificationTable.tsx
> +  const [notificationInfo, setNotificationInfo] = useState<INotificaionTable>();
inital state가 없네용 
{
    notiList: [],
    totalPage: 0,
    currentPage: 0,
}
이런 식으로라도 있는게 좋을 것 같습니다 ?!

2023-02-08 06:18 UTC, raehy19 commented on styles/admin/common/AdminSearchBar.module.scss
> +  // margin: 1rem 0.8rem 11px;
무슨 의미의 주석인가용 ?

2023-02-08 06:18 UTC, raehy19 commented on components/admin/notification/NotificationTable.tsx
> +import { useCallback, useEffect, useState } from 'react';
import 순서 code rule에 맞춰서 수정해주시면 좋을것같아요 !

2023-02-08 06:29 UTC, mike2ox commented on styles/admin/common/AdminSearchBar.module.scss
> +  // margin: 1rem 0.8rem 11px;
<img width="886" alt="스크린샷 2023-02-08 오후 3 28 14" src="https://user-images.githubusercontent.com/22931103/217451797-4991c76f-c741-4e32-a470-e95eafc5a7ee.png">
실 서비스의 searchBar의 margin인데 스타일 참고하다가 의미없는 margin이길래 주석처리하고 스타일 작업했었습니다.
admin에서는 필요없는 스타일이라 삭제하도록 할게요

2023-02-08 06:30 UTC, mike2ox commented on components/admin/notification/NotificationTable.tsx
> +  const [notificationInfo, setNotificationInfo] = useState<INotificaionTable>();
초기값 중요하다가 제가 막 말하면서 정작 제가 안넣었네요 ㅎㅎ;;;
수정하도록 할게요

2023-02-08 06:30 UTC, mike2ox commented on components/admin/notification/NotificationTable.tsx
> +import { useCallback, useEffect, useState } from 'react';
import order rule 있는걸 까먹었네요 수정해서 올리도록 하겠습니다.

2023-02-08 08:39 UTC, raehy19 approved these changes
수정하신거 확인했습니다 고생하셨습니다 !!

2023-02-09 11:24 UTC, 42sungwook commented
`현재 SearchBar에 initSearch라는 함수를 전달하는 방식으로 기존 SearchBar을 그대로 쓰고 있는데 코드를 copy&paste해서 admin용으로 새로 분리를 하는게 맞을지 의문입니다.` -> 이 부분은 기획 단계에서 얘기했을 때 backend에 정확한 intraId값을 주지 않고 일부만 보내줘도 해당 값이 포함된 intraId를 전부 보내준다고 해서 지금의 검색방식이 맞지는 않은 것 같습니다

2023-02-09 12:18 UTC, mike2ox commented
> `현재 SearchBar에 initSearch라는 함수를 전달하는 방식으로 기존 SearchBar을 그대로 쓰고 있는데 코드를 copy&paste해서 admin용으로 새로 분리를 하는게 맞을지 의문입니다.` -> 이 부분은 기획 단계에서 얘기했을 때 backend에 정확한 intraId값을 주지 않고 일부만 보내줘도 해당 값이 포함된 intraId를 전부 보내준다고 해서 지금의 검색방식이 맞지는 않은 것 같습니다 하지만 지금 쓰는데는 문제가 없어 이슈를 남겨놓고 나중에 바꿔도 될 것 같아요 ex) mo만 검색해도 mosong mosong1 mosong2 유저들을 api로 불러오는게 가능

여기서 mo만 검색했을때 mosong1, mosong2가 안뜨는건 당연합니다... 저건 admin용 API가 아니라 매칭 서비스용 API를 그대로 갖다쓴거라서 그렇습니다. 말씀하신 부분은 노션에서 `/admin/users/searches?q=${keyword}` 이 부분인데 배포가 안되있어서 매칭 서비스용 API를 붙여놓은 상태에요

2023-02-09 12:24 UTC, 42sungwook commented
아 그 부분이 문제가 아니었군요. 코드를 그대로 복붙하는게 별로여서 물어보신거라면 서치바를 인터페이스로 만들어서 admin용을 분리해서 쓰는건 어떤가요..?

2023-02-09 21:35 UTC, mike2ox commented
@42sungwook OOP의 interface 개념을 적용하면 좋긴하지만 해당 사례는 HOC를 적용해 보는게 좋지않을까 싶네요

HOC 참고 : https://satisfactoryplace.tistory.com/163

2023-02-10 02:40 UTC, merged