Feat/관리자 유저 모달 개선 #647
42organization/42gg.client pull request #649
Opened 2023-02-11 07:07 UTC by 42sungwook

## 📌 개요
  - 타입과 초기값 지정으로 생긴 오류 수정
 ## 💻 작업사항
 - 버튼 클릭 영역 수정
 - inputHandler타입 문제 해결
 - userInfo 초기값 설정
 - number 형태의 데이터만 따로 처리해주는 eventHandler 제작
 - 숫자가 없을 때 NaN표시 -> 0으로 수정
 - import 순서 맞추기
 - 불변성 유지하는 방법이 여러가지가 있는데 [참고](https://leehwarang.github.io/docs/tech/2020-03-15-object.html)
 - image 태그 alt 채우기 [참고](https://hi-seo.co.kr/seo-contents/seo-%EC%BD%98%ED%85%90%EC%B8%A0-%EC%B5%9C%EC%A0%81%ED%99%94/alt-%ED%83%9C%EA%B7%B8%EC%9D%98-%EC%A4%91%EC%9A%94%EC%84%B1%EA%B3%BC-%EC%9E%91%EC%84%B1-%EB%85%B8%ED%95%98%EC%9A%B0/)
 - Props 타입명 수정
 - userInfo 타입 ''을 null로 수정 -> HTMLInputElement는 null타입이 없고 num, string, ..., undefined 형식만 존재
 - statusMessage 30자로 제한
 
## ETC
이전 branch 에서 작업하던 PR: [링크](https://github.com/42organization/42gg.client/pull/645)

2023-02-13 10:19 UTC, mike2ox reviewed
주말간에 모달 스타일에 신경쓰신게 많이 보이네요 고생하셨습니다!
몇가지 코멘트 남겨드린거 답변 달아주시면 되겠고 사진 업로드 관련해서 아래 이슈 확인 부탁드립니다.

- 업로드할 사진 미리보기는 되지만 정작 전송(변경)버튼을 클릭하면 userInfo안에는 업로드 전 사진 url이 담겨있습니다.

2023-02-13 10:19 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +    setUserInfo({ ...userInfo, [name]: value });
useRef를 사용해서 기존에 저장되있는 값과 비교해서 userInfo의 특정 property를 갱신 해주는 방식은 어떨까요?
비교후 일치하면 setUserInfo로 리렌더하는걸 방지할 수 있을거 같아요.

2023-02-13 10:19 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +    if (isNaN(intValue)) {
여기서 isNaN을 통해 검증 로직을 추가하지 말고 input 고유 옵션을 이용해보면 어떨까요?(type='number')

2023-02-13 10:19 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +                  alt='Profile Image'
웹 접근성과 이미지 불러오기 실패시 보여줄 alt 정보 기입! 좋습니다.

2023-02-13 10:19 UTC, mike2ox commented on types/admin/adminUserTypes.ts
>    modalName?: 'ADMIN-PROFILE';
지금보니 modalName이 전달되는 케이스가 없어서 삭제해도 무방해 보입니다!

2023-02-13 10:19 UTC, mike2ox commented on styles/admin/modal/AdminProfile.module.scss
> +  align-items: center;
button마다 border: none을 넣어주면 현재 버튼에서 보이는 버튼 기본 테두리가 안보일거 같네요

2023-02-14 03:25 UTC, Wilbur0306 commented
모달을 만드는 완전 처음부터 지금까지의 과정을 옆에서 지켜본 사람으로서 기능적인 부분도 당연하지만, 디자인적으로 변한게 많은 것이 확 느껴졌습니다. NaN으로 표시되어서 고쳐야했던 부분도 말끔하게 수정해주신 것을 확인할 수 있었습니다! 수정하시느라 수고 많으셨습니다!

2023-02-14 03:27 UTC, Wilbur0306 reviewed
모달을 만드는 완전 처음부터 지금까지의 과정을 옆에서 지켜본 사람으로서 기능적인 부분도 당연하지만, 디자인적으로 변한게 많은 것이 확 느껴졌습니다. NaN으로 표시되어서 고쳐야했던 부분도 말끔하게 수정해주신 것을 확인할 수 있었습니다! 수정하시느라 수고 많으셨습니다!

2023-02-14 06:01 UTC, raehy19 requested changes
수고하셨습니다 !! 모송님이 많이 써주셔서 크게 더 고칠게 없는거같기도 한데 사소한 코멘트 확인 부탁드립니다 ~

2023-02-15 08:57 UTC, raehy19 requested changes
수고하셨습니다 큰 문제는 없는데 리팩토링할만한 요소가 있는것같아서 소소한 코멘트 확인해주시면 될거같아요 ~

2023-02-15 08:57 UTC, raehy19 commented on components/modal/admin/AdminProfileModal.tsx
>  import { useEffect, useState } from 'react';
import 순서 !!

2023-02-15 08:57 UTC, raehy19 commented on hooks/useUploadImg.ts
> +    console.log(e);
console log가 있네용 ?

2023-02-15 08:57 UTC, raehy19 commented on components/modal/admin/AdminProfileModal.tsx
> +const CHAR_LIMIT = 30;
char limit 보다는 status msg limit 등으로 변수명을 짓는 게 더 좋아보입니다 !

2023-02-15 08:57 UTC, raehy19 commented on styles/admin/modal/AdminProfile.module.scss
> +  border: none;
css 도 순서를 맞추는것이 보기 편합니당 ! code rule에 css order 도 있어요 !
https://github.com/42organization/42gg.client/wiki/Code-rules

2023-02-15 09:14 UTC, mike2ox commented on styles/admin/modal/AdminProfile.module.scss
> +  border: none;
CSS 순서도 있었군요. 저도 수정해서 올려야겠네요

2023-02-15 09:30 UTC, mike2ox requested changes
필요없는 주석은 삭제해주시고 래현님 말씀처럼 역할이 끝난(main에 붙이는 PR에서) console.log는 삭제해주시는게 좋습니다.
admin/users.tsx에서 intraId가 하드코딩되어 있던데 유저관리 페이지에 table 만들어서 올려드리도록 할게요

2023-02-15 09:30 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +    | React.ChangeEvent<HTMLTextAreaElement>
React.ChangeEvent 앞에 `|` 가 붙는게 맞는건가요?

2023-02-15 09:30 UTC, mike2ox commented on hooks/useUploadImg.ts
>        console.log(error);
일반 error 표기 말고 error용 modal을 띄우시거나 console.error('구분 가능한 값')로 에러 로그로 표기되도록 해주세요

2023-02-15 09:30 UTC, mike2ox commented on pages/api/admin/users/index.ts
> +      email: '42gg@42seoul.kr',
AdminProfileModal에서는 eMail 그대로 있던데 어떤게 맞는걸까요?

2023-02-17 01:42 UTC, 42sungwook commented on components/modal/admin/AdminProfileModal.tsx
>  import { useEffect, useState } from 'react';
엥 import 순서를 맞춘건데 어떻게 바꿔야하나요?
wiki상 요렇게가 순서에요..
```
next             - from 'next/*'
react            - from 'react/*'
recoil           - from 'recoil'
types            - from 'type/*'
utils            - from 'utils/*'
components       - from 'components/*'
[icon]           - from 'react-icons/*'
styles           - from 'styles/*'
```

2023-02-17 01:58 UTC, 42sungwook commented on components/modal/admin/AdminProfileModal.tsx
> +    | React.ChangeEvent<HTMLTextAreaElement>
넵 지우려해도 prettier에서 자동으로 넣어주네요!

2023-02-17 02:24 UTC, 42sungwook commented on pages/api/admin/users/index.ts
> +      email: '42gg@42seoul.kr',
eMail이 맞습니다. 명세 수정되었습니다

2023-02-17 08:21 UTC, mike2ox approved these changes
고생하셨습니다!

2023-02-17 08:21 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +    setUserInfo(res?.data);
try - catch 로 실패시 에러로깅 남겨주죠

2023-02-18 05:33 UTC, raehy19 approved these changes
lgtm~ 수고하셨습니다 !

2023-02-18 11:54 UTC, merged