Feat/toast message 최종 개선 #650
42organization/42gg.client pull request #668
Opened 2023-02-20 06:30 UTC by Wilbur0306

## 📌 개요 
  - toast message 최종 수정
 ## 💻 작업사항 
- [ ] 저번 PR 리뷰에서 받은 커멘트들 기반으로 toast message 최종 수정
- [ ] 관리자 전체 유저 알림 모달과 toast message 기능 연결

##시현
1. `npm i & npm run dev` 실행한다
2. 브라우저에서 "localhost:3000/admin" 접속 후 관리자 페이지의 "알림 관리" 들어간다
3. 우측 상단에 있는 "All" 버튼을 누른다
4. [적용] 버튼을 누른 뒤 좌측 하단에 뜨는 Success 토스트 메세지 확인

## 관련 이슈
- #655 
- #650

2023-02-20 07:17 UTC, 42sungwook requested changes
고생하셨습니다. 몇가지만 수정해주시면 될 것 같아요

2023-02-20 07:17 UTC, 42sungwook commented on components/modal/admin/AdminNotiAllModal.tsx
> +
중복된 코드인 것 같아요!

2023-02-20 07:17 UTC, 42sungwook commented on components/modal/admin/AdminNotiAllModal.tsx
> -
이 부분은 삭제가 맞나요?

2023-02-20 07:17 UTC, 42sungwook commented on components/modal/admin/AdminNotiAllModal.tsx
> +  const finishEditHandler = () => setModal({ modalName: null });
이 핸들러가 현재 안쓰이는데 handleclick에 넣으시면 될 것 같아요

2023-02-20 07:17 UTC, 42sungwook commented on components/toastmsg/toastmsg.tsx
> +    }
이 부분은 어떤 경우인가요?

2023-02-20 07:36 UTC, Wilbur0306 commented on components/toastmsg/toastmsg.tsx
> +    }
현재 페이지 또는 모달 내에서 띄워지고 있는 toast message가 다른 화면을 눌렀을 때 사라지는 상황을 의미합니다!
AdminNotiAllModal은 모달 창 밖을 클릭하면 모달이 사라지도록 구현이 되어있어서 확인하기 어려우셨을 수도 있는데, 
상단의 조건문의 유무에 따라 모달 창 "안"을 클릭 했을 때 toast messgae가 사라지고, 안 사라지고에 차이가 있습니다.

2023-02-20 07:37 UTC, Wilbur0306 commented on components/modal/admin/AdminNotiAllModal.tsx
> -
삭제가 맞습니다

2023-02-20 07:37 UTC, Wilbur0306 commented on components/modal/admin/AdminNotiAllModal.tsx
> +
확인하였습니다. 삭제하도록 하겠습니다

2023-02-20 07:39 UTC, Wilbur0306 commented on components/modal/admin/AdminNotiAllModal.tsx
> +  const finishEditHandler = () => setModal({ modalName: null });
[적용] 버튼을 눌렀을 때에 Success 토스트 메세지가 띄워짐과 동시에 모달 창만 닫히는 것으로 구현을 해야할지, 아니면 모달 창은 그대로 있는 상태에서 토스트 메세지만 띄워져야할지 상의 후 결정 나는 로직대로 수정하겠습니다!

2023-02-21 02:16 UTC, 42sungwook commented
지금 모달창이 꺼지면 토스트 메시지도 사라지는 종속관계인데  recoil을 사용해서 독립적으로 메시지를 띄우게 바꿔보시면 좋을 것 같습니다!

2023-02-21 03:03 UTC, mike2ox commented on components/modal/admin/AdminNotiAllModal.tsx
> +  const finishEditHandler = () => setModal({ modalName: null });
이거는 알림 보낸게 table에 그대로 남으니까 모달창 꺼줘도 될꺼 같아요.

2023-02-21 05:28 UTC, mike2ox reviewed
고생하셨습니다! 빠르게 건의했던거 확인하시고 내일 회의전에 수정후 컨펌 받으시고 merge gogo!!!

2023-02-21 05:28 UTC, mike2ox commented on components/modal/admin/AdminNotiAllModal.tsx
> +import CustomizedSnackbars from 'components/toastmsg/toastmsg';
import order convention 관련해서 자동화 할 수 있게 알아보고 있으니
이번 PR까지는 수동으로 맞춰주세요

2023-02-21 05:28 UTC, mike2ox commented on components/modal/admin/AdminNotiAllModal.tsx
> +  const finishEditHandler = () => setModal({ modalName: null });
그리고 finishEditHandler와 cancelEditHandler 둘다 동작 로직이 동일해서 개선이 필요해 보여요
finishEditHandler같은 경우 동작 시 toast가 어떤 형식으로든 나타날 테니 finishEditHandler 부븐을 수정하면 어떨까요?

2023-02-21 05:28 UTC, mike2ox commented on components/modal/admin/AdminNotiAllModal.tsx
> +    setOpen(true);
하드코딩도 좋지만 open의 기본값이 `false`니까
```ts
setOpen((prev) => !prev); 
```
로 하는건 어떨까요?

2023-02-21 05:28 UTC, mike2ox commented on components/modal/admin/AdminNotiAllModal.tsx
> +          <textarea
따로 입력길이 제한은 안넣는걸까요?
기존 notification 데이터 저장할 때 제한 조건이 없었다면 사용자측에 보여지는 방식을 한번 봐야할 거 같네요. (ex. 입력 데이터가 너무 길 경우)

2023-02-21 05:28 UTC, mike2ox commented on components/modal/admin/AdminNotiAllModal.tsx
> +          />
recoil을 사용해서 snackbar를 해당 modal에서 독립되도록 해주시죠

2023-02-21 05:28 UTC, mike2ox commented on components/toastmsg/toastmsg.tsx
> +import { forwardRef, useEffect, useState } from 'react';
여기도 import order convention 체크 해주세요

2023-02-21 05:28 UTC, mike2ox commented on components/toastmsg/toastmsg.tsx
> +});
몇가지 궁금한게 있어서 설명해주시면 좋을거 같습니다!

- forwardRef의 기능
- MuiAlert에서 elevation의 역할

2023-02-21 05:28 UTC, mike2ox commented on components/toastmsg/toastmsg.tsx
> +    }
찾아보니 clickaway말고도 2개가 더 있네요. escapeKeyDown까지는 넣어도 될꺼 같네요
```
export type SnackbarCloseReason = 'timeout' | 'clickaway' | 'escapeKeyDown';
```

2023-02-21 05:28 UTC, mike2ox commented on components/toastmsg/toastmsg.tsx
> +      <Snackbar open={open} autoHideDuration={6000} onClose={handleClose}>
autoHideDuration에 들어가는 인자도 상수화 해주는게 좋을거 같네요.
현재 main에 constants 폴더 안에 구성해 놓은게 있으니 merge하셔서 확인해보세요

2023-02-21 05:28 UTC, mike2ox commented on styles/admin/modal/AdminNotiAll.module.scss
> +  align-items: center;
스타일쪽도 convention이 있더라구요. 확인해주세요

2023-02-21 07:23 UTC, Wilbur0306 commented on components/modal/admin/AdminNotiAllModal.tsx
> +    setOpen(true);
수정하였습니다!

2023-02-21 07:26 UTC, Wilbur0306 commented on components/toastmsg/toastmsg.tsx
> +    }
'escapeKeyDown' 추가하였습니다!

2023-02-21 07:35 UTC, Wilbur0306 commented on components/toastmsg/toastmsg.tsx
> +import { forwardRef, useEffect, useState } from 'react';
수정했습니다!

2023-02-21 07:37 UTC, Wilbur0306 commented on components/modal/admin/AdminNotiAllModal.tsx
> +import CustomizedSnackbars from 'components/toastmsg/toastmsg';
넵! 수정했습니다

2023-02-21 07:42 UTC, Wilbur0306 commented on styles/admin/modal/AdminNotiAll.module.scss
> +  align-items: center;
확인하고 수정했습니다!

2023-02-21 08:22 UTC, raehy19 requested changes
수고 많으셨습니당 소소한 코멘트 확인해주세요 !

2023-02-21 08:22 UTC, raehy19 commented on components/toastmsg/toastmsg.tsx
> +export default function CustomizedSnackbars({
파일이름과 컴포넌트 이름은 같은게 보기 좋을것같아요 !

2023-02-21 08:22 UTC, raehy19 commented on components/toastmsg/toastmsg.tsx
> +    }
&& 써서 한줄로 줄일 수 있을 것 같은데 

찾아보니까 https://stackoverflow.com/questions/34704750/one-line-if-vs-in-javascript

&& 을 이용한 구문이 그렇게 좋은 건 아니네요..?

그래도 if (clicked) setOpen(true); 로 한줄로 줄이는게 이쁠거 같아요 !

2023-02-21 08:22 UTC, raehy19 commented on components/toastmsg/toastmsg.tsx
> +      return;
요것도 한줄로 고치는게 이쁠거같습니당

2023-02-21 08:22 UTC, raehy19 commented on styles/admin/modal/AdminNotiAll.module.scss
> +  align-items: center;
align-items 이 친구는 display flex 관련 속성이라 위에 있는게 맞을거같아요 !

2023-02-21 08:22 UTC, raehy19 commented on styles/admin/modal/AdminNotiAll.module.scss
> +  align-items: center;
여기도 align-items !

2023-02-21 08:22 UTC, raehy19 commented on components/modal/admin/AdminNotiAllModal.tsx
> +          <textarea
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/69339099/220287487-2ebdc642-1cb0-4636-879d-aa533356daa1.png">
textarea 를 사용하셔서 사용자가 입력창 크기를 조절 가능한데 resize: none 주면 막을수 있었던것같아요

2023-02-21 08:22 UTC, raehy19 commented on components/modal/admin/AdminNotiAllModal.tsx
> +  const finishEditHandler = () => setModal({ modalName: null });
모송님 의견에 동의합니다 짧은 내용이라 handler를 굳이 함수로 선언하기보다는 사용하는곳에 화살표함수로 setmodal null을 실행하는것도 좋을것같다고 생각해용

2023-02-22 07:49 UTC, Wilbur0306 commented on components/modal/admin/AdminNotiAllModal.tsx
> +          />
mosong님과 수정 완료!

2023-02-22 07:50 UTC, Wilbur0306 commented on components/toastmsg/toastmsg.tsx
> +    }
한 줄로 수정하였습니다!

2023-02-22 07:53 UTC, Wilbur0306 commented on styles/admin/modal/AdminNotiAll.module.scss
> +  align-items: center;
위로 올려놨습니다!

2023-02-22 07:53 UTC, Wilbur0306 commented on styles/admin/modal/AdminNotiAll.module.scss
> +  align-items: center;
위로 올려놨습니다!

2023-02-22 08:09 UTC, Wilbur0306 commented on components/modal/admin/AdminNotiAllModal.tsx
> +          <textarea
수정하였습니다!

2023-02-22 08:15 UTC, Wilbur0306 commented on components/toastmsg/toastmsg.tsx
> +      return;
한 줄로 줄였습니다!

2023-02-22 08:17 UTC, Wilbur0306 commented
> 지금 모달창이 꺼지면 토스트 메시지도 사라지는 종속관계인데 recoil을 사용해서 독립적으로 메시지를 띄우게 바꿔보시면 좋을 것 같습니다!

2023-02-22 08:18 UTC, closed without merging