Feat/유저 모달 에러 관리 #666
42organization/42gg.client pull request #671
Opened 2023-02-21 10:13 UTC by 42sungwook

## 📌 개요 
이미지 압축기능 추가
토스트로 오류 처리 (아직 토스트가 완성되지 않아서 주석으로 처리)
여러가지 에러 처리
 ## 💻 작업사항 

- 정보가 수정되지 않았을 때 보내는 방식 수정
    - 이미지는 수정되지 않으면 폼데이터에서 제거
    - 이미지 제외 모든 정보는 수정 여부에 상관없이 폼데이터에 추가
- 에러 수정
    - 404 에러 수정 (유저 이미지 초기값이 null인 상태로 렌더링하여 띄워주려해서 생긴 현상)
    - 이미지 정보를 받아도 모달에 뜨지 않는 현상 해결
       (이미지 태그의 width, height 값이 실제 이미지 크기보다 작아서 생김 -> 압축으로 크기 지정)
- 압축 기능 추가
    - browser-image-compression 라이브러리를 사용하는데 에러 발생 해결
      (현재 custom hook으로 파일 업로드를 따로 빼서 관리하는데 export하는 함수에 async를 제거하여 해결)
    - 압축하고 보내는데 타입 관련해서 문제가 지속적으로 발생 해결
      (압축된 imgData를 제대로 보내지 않아 생긴 문제)
- 에러 상태 수정
      (200 정상, 207 랭크정보만 없어서 수정 불가, 400 잘못된 요청, 401 권한 없음, 413 파일 용량제한 에러, 415 파일 확장자 에러)
      - 토스트 메시지로 처리
- 프로필 이미지가 없는 경우
    - 현재 유저에게 보여지는 프로필은 돔의 규격에 맞지 않으면 다스베이더를 보여줍니다
      하지만 관리자에게 다스베이더를 보여줄 필요는 없다고 판단하여 alt 메세지 수정
      관리자가 이미지를 바꿔주면 이미지 압축을 맞게 해주어 문제 없을 것으로 판단 (사용자가 보는 프로필 이미지는 다시 확인 필요)
 
 
## 추가 필요한 작업
- 유저가 보는 페이지의 프로필 이미지가 관리자 페이지에서 압축시킨 이미지의 규격에 맞는지 확인 필요
- 토스트 메세지 붙이기
- 207상태를 200상태와 다르게 처리하는 작업 필요
- input의 value가 null일 때 warning이 뜨는 경우 수정 필요

2023-02-22 02:50 UTC, Wilbur0306 approved these changes
수고 많으셨습니다! toast message 부분이 완성되지 않아 아직 진행하지 못한 부분이 있으셔서 괜히 죄송하네요🥲 오늘 얼른 merge 시키도록 하겠습니다!

2023-02-22 08:52 UTC, mike2ox reviewed
사진 업로드 형식 맞추시느라 고생하셨어요
몇가지만 수정하시면 될거 같습니다!

2023-02-22 08:52 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +                    alt='이미지가 규격에 맞지 않거나 없습니다'
alt는 사진이 없을 때 대신 띄어줄 텍스트 제공 용도라 경고 메세지는 적합하지 않나 생각이 드네요

참고 : http://www.tcpschool.com/html-tag-attrs/img-alt

2023-02-23 07:38 UTC, 42sungwook commented on components/modal/admin/AdminProfileModal.tsx
> +                    alt='이미지가 규격에 맞지 않거나 없습니다'
참고 사이트에 '어떤 이유로든' 이미지를 띄울 수 없을 때 alt를 쓴다는데 단순히 제가 짠 컴포넌트의 규격에 맞지 않아 보여주지 못하는 것인데 없는 것처럼 표기가 되는 것이 마음에 들지 않아 저렇게 썼어요(관리자 입장)
이미지는 있는데 컴포넌트 크기보다 커서 나타나지 않을 때 어떻게 하는 것이 좋을까요? 없는 것과 동일하게 alt='profile image'로 나타내는게 맞다고 생각하시나요?

2023-02-24 01:11 UTC, raehy19 commented on components/modal/admin/AdminProfileModal.tsx
> +                    alt='이미지가 규격에 맞지 않거나 없습니다'
이제 이미지가 정방향이 아니여도 잘 나오는거 같은데 규격에 안맞아서 안나오는 경우가 아직 있나요 ?

2023-02-24 01:14 UTC, raehy19 approved these changes
수고하셨습니다 ! lgtm~ image alt 만 조금 생각해보면 좋을것같아요

2023-02-24 01:48 UTC, 42sungwook commented on components/modal/admin/AdminProfileModal.tsx
> +                    alt='이미지가 규격에 맞지 않거나 없습니다'
관리자가 넣어준 이미지는 규격에 맞는데 애초에 intra에 등록되어있는 이미지가 규격에 안맞으면 다스베이더로 나오더라고요

2023-02-27 08:17 UTC, raehy19 requested changes
수고하셨습니다 ! 그런데 토스트로 바뀌면서 문제될것같은게 있네요
수정완료 토스트 메시지를 닫지 않은 상태로 수정을 한번 더 해도 토스트 메시지가 전혀 변동이 없어서 관리자 입장에서는 수정이 되었는지 안되었는지를 알 수 없을 것 같아요

수정완료 토스트 메시지를 띄우면서 모달을 닫거나 토스트 메시지를 닫지 않은 상태에서 한번 더 수정을 해도 사용자가 수정되었다는것을 알 수 있게 하는 게 좋을 것 같습니다

그리고 모달에서 수정과 취소 버튼 cursor pointer 해주시는게 좋을것같습니다 !!!

2023-02-27 08:17 UTC, raehy19 commented on components/admin/users/UserManagementTable.tsx
> +        //  setModal({ modalName: 'ADMIN-PENALTY', userId });
아직 페널티 모달 없어서 그런것같은데 주석처리되어있어서 TODO 적어줘도 좋을것같아용

2023-02-27 11:34 UTC, 42sungwook commented
@raehy19  말씀하신 내용 모두 수정했습니다!

2023-02-27 11:34 UTC, 42sungwook commented on components/admin/users/UserManagementTable.tsx
> +        //  setModal({ modalName: 'ADMIN-PENALTY', userId });
모달 이미 있어서 붙였습니다!

2023-02-28 02:25 UTC, raehy19 approved these changes
확인했습니다 고생 많으셨습니다 !!

2023-02-28 02:47 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +    ppp: '',
여기를 ''도 받을 수 있도록 하신 이유가 있으신가요?

2023-02-28 02:47 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +      }
분기처리를 잘해주셨네요 👍 
요부분 main에 합치면 제가 interceptor안으로 넣도록 하겠습니다

2023-02-28 02:47 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +                {userInfo.userImageUri && (
이 구분이 들어가는 이유가 궁금하네요.
userImageUri가 없으면 imgPreview를 보여주는 방식이었던 걸로 아는데
이렇게 조건을 걸어두시면 userImageUri가 없으면 비어있는 영역이 한순간 생길거거든요

2023-02-28 02:47 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +                    value={userInfo.email ?? ''}
옵셔널 체이닝과 널리쉬 콜레싱을 쓰시길래 복습겸 자료 조사를 해봤습니다.
관련 문법을 모르는 분들도 보면 좋을거 같아요.

참고 : https://velog.io/@dwseo96/TIL-optional-chaining%EC%98%B5%EC%85%94%EB%84%90-%EC%B2%B4%EC%9D%B4%EB%8B%9D-nullish-coalescing%EB%84%90%EB%A6%AC%EC%89%AC-%EC%BD%9C%EB%A0%88%EC%8B%B1

2023-02-28 02:47 UTC, mike2ox commented on hooks/useUploadImg.ts
> +      });
얘같은 경우 axios interceptor쪽에서 걸리지 않는 error handling이라 이대로 넣어두시면 될거 같아요.
`clicked: false` 여기부분때문에 toast 창이 안뜰거 같은데 제대로 동작하던가요

2023-02-28 04:39 UTC, 42sungwook commented on components/modal/admin/AdminProfileModal.tsx
> +    ppp: '',
유저의 승,패,ppp 정보가 없으면 정보가 null로 날아올거라고 하셔서 바꿨습니다
타입에 숫자만 들어갈 수 있으면 에러가 날 수 있다고 생각했어요

2023-02-28 04:41 UTC, 42sungwook commented on components/modal/admin/AdminProfileModal.tsx
> +                    value={userInfo.email ?? ''}
참고자료 감사합니다! 저도 복습겸 다시 볼게요👍👍

2023-02-28 04:53 UTC, 42sungwook commented on components/modal/admin/AdminProfileModal.tsx
> +                {userInfo.userImageUri && (
비어있는 영역이 생기는게 맞습니다
스타일적으로는 styles.image에 크기가 정해져있어 깨지지는 않습니다

이렇게 한 이유는 처음에 detail정보를 가져오기 전에 userInfo.userImageUri가 null이어서 경고가 생겨 이렇게 바꿨습니다.

2023-02-28 04:54 UTC, 42sungwook commented on hooks/useUploadImg.ts
> +      });
헛 좋은 지적 감사합니다. 따로 테스트를 안해봤는데 바꿔놓겠습니다!

2023-02-28 06:47 UTC, mike2ox commented on components/modal/admin/AdminProfileModal.tsx
> +                {userInfo.userImageUri && (
현시점에선 default가 null보단 다스베이더 화이트버전이 UX적으로 나을거 같고
시간을 들이실거면 getstaticprops 같은 Next.js 함수를 써서 사전에 데이터를 가져오는게 제대로 Next.js를 쓰는 방식일거 같네요.

2023-02-28 06:48 UTC, mike2ox approved these changes

2023-02-28 07:32 UTC, 42sungwook commented on components/modal/admin/AdminProfileModal.tsx
> +                {userInfo.userImageUri && (
다스베이더로 바꾸고 userImageUri 조건은 삭제해봤는데 똑같이 404 에러를 띄워서 일단 이대로 올리고 버그 이슈를 남겨놓겠습니다

2023-03-01 02:39 UTC, merged