[Feat] 관리자 유저 관리 패널티 모달 CSS 수정 #703
42organization/42gg.client pull request #704
Opened 2023-03-01 11:26 UTC by Wilbur0306

## 📌 개요 
  - 관리자 유저 관리 패널티 모달 CSS 수정
 ## 💻 작업사항 
  - [X] 관리자 페이지의 유저 관리 카테고리 패널티 모달 부분 피그마 디자인에 맞게 CSS 수정하기
 ## 확인 방법
 1. `npm i && npm run dev` 실행
 2. 관리자 페이지로 이동
 3. 유저 관리 카테고리로 이동
 4. 아무 [패널티 부여] 버튼 클릭
 5. 디자인이 바뀐 패널티 모달 확인

## 관련 이슈
- #703

2023-03-01 15:10 UTC, 42sungwook requested changes
고생하셨습니다! CSS 설정이 정말 많이 늘었네요! 반복되는 설정이 좀 보여서 저도 이런 부분을 어떻게 처리하는지 좀 찾아봤는데 참고하셔서 바꿀 수 있는 부분은 바꾸는게 더 깔끔해 보일 것 같아요 [참고 사이트](https://guiyomi.tistory.com/133)

추가로 placeholder의 위치가 지금 박스 상단에 붙어있는데
```
.durationWrap textarea::placeholder {
  line-height: 
}
```
와 같은 설정으로 위치 조정할 수 있어요!

2023-03-01 23:21 UTC, raehy19 commented on components/modal/admin/AdminPenaltyModal.tsx
> +            />
페널티를 부여할 사람의 intraId 입력란인거 같습니다 !

2023-03-01 23:44 UTC, raehy19 requested changes
페널티 모달도 예뻐졌네요 수고하셨습니다 ! 코멘트 확인해주시고 사소한 부분만 고치면 될거같아용

2023-03-01 23:44 UTC, raehy19 commented on components/modal/admin/AdminPenaltyModal.tsx
> +            <textarea
날짜는 textarea로 받으면 예외처리 해야할 게 많을 것 같아서 input의 type='date'를 주면 날짜선택해서 입력받을 수 있어요 !

2023-03-01 23:44 UTC, raehy19 commented on components/modal/admin/AdminPenaltyModal.tsx
> +            <textarea
저번 회의 때 어떻게 정했는지 기억이 잘 안나는데 기간과 날짜 둘 중 하나만 받아도 의미는 동일하지 않을까 라는 생각이 드네요 아니면 차라리 해제되는 날의 시간도 입력받는건 어떨까 싶습니다 !

2023-03-01 23:44 UTC, raehy19 commented on components/modal/admin/AdminPenaltyModal.tsx
> +      <label className={styles.body}>
라벨태그를 사용하셔서 모달 안 textarea 외 다른 부분을 선택해도 첫 번째 textarea인 intraId 입력 부분으로 포커스가 가네요 ! 이렇게 하신 이유가 궁금합니당

2023-03-01 23:44 UTC, raehy19 commented on components/modal/admin/AdminPenaltyModal.tsx
> +import { useCallback, useEffect, useState } from 'react';
사용하지 않는 import들이 있습니당

2023-03-01 23:44 UTC, raehy19 commented on styles/admin/modal/AdminPenalty.module.scss
> +  flex-wrap: reverse;
flex-wrap에 reverse라는 프로퍼티는 없는 프로퍼티라서 지금은 의미없는 구문입니당 wrap-reverse를 사용하셔야되고 성욱님 말씀대로 불필요해 보입니다 !

2023-03-02 02:38 UTC, Wilbur0306 commented on components/modal/admin/AdminPenaltyModal.tsx
> +            />
맞습니당!

2023-03-02 02:48 UTC, Wilbur0306 commented on styles/admin/modal/AdminPenalty.module.scss
> +  flex-wrap: reverse;
수정했습니다

2023-03-02 03:10 UTC, Wilbur0306 commented on components/modal/admin/AdminPenaltyModal.tsx
> +            <textarea
수정했습니다!!

2023-03-02 04:02 UTC, Wilbur0306 commented on components/modal/admin/AdminPenaltyModal.tsx
> +      <label className={styles.body}>
실수입니당.. 수정했습니다!

2023-03-02 04:02 UTC, Wilbur0306 commented on components/modal/admin/AdminPenaltyModal.tsx
> +import { useCallback, useEffect, useState } from 'react';
삭제하였습니다!

2023-03-02 04:03 UTC, Wilbur0306 commented on styles/admin/modal/AdminPenalty.module.scss
> +  flex-wrap: reverse;
넵! 삭제하였습니다!

2023-03-02 04:03 UTC, Wilbur0306 commented on components/modal/admin/AdminPenaltyModal.tsx
> +      <label className={styles.body}>
div 태그로 바꿔주는 것을 까먹고 놔뒀네요. 수정했습니다!

2023-03-02 04:29 UTC, Wilbur0306 commented on components/modal/admin/AdminPenaltyModal.tsx
> +            <textarea
현재 디자인 시안이 적용기간과, 해당 날짜를 모두 받는 형태로 되어 있어서 일단은 시안은 기준으로 만들었는데 나중에 로직이 바뀌게 되면 수정하도록 하겠습니다!

2023-03-02 07:24 UTC, closed without merging