Feat/관리자 특정 유저 모달 api 붙이기 #709
42organization/42gg.client pull request #712
Opened 2023-03-06 07:59 UTC by Wilbur0306

## 📌 개요 
  - 특정 유저 알림 모달에 API  붙이기
 ## 💻 작업사항 
- [X] 관리자 특정 유저 알림 모달 API 붙이기
## 확인 방법
1. `npm i && npm run dev`실행
2. 알림 관리 페이지로 이동
3. 우측 상단의 [User] 버튼 클릭
4. 여러 가지 상황들을 마구 넣어보며 그 상황에 맞는 에러/성공 토스트 메시지가 나오는지 확인
5. 최종적으로 올바른 인트라ID(본인 인트라)를 작성하고 알림을 작성하였을 때 알림이 잘 오는지 서버들어가서 확인

##관련 이슈
- #709

2023-03-07 02:54 UTC, mike2ox reviewed
setSnackBar같은 경우 setState와 결이 같으니 setState가 비동기 처리된다는걸 알고 조사하시면 setState를 더 잘 쓸수있으라거라 봅니다

2023-03-07 02:54 UTC, mike2ox commented on components/modal/admin/AdminNotiUserModal.tsx
>  let timer: ReturnType<typeof setTimeout>;
저는 아래 코드처럼 작성해서 런타임 환경을 구분해서 타입지정을 했는데 위와같은 방식을 하면 한번에 해결되네요 

```ts
let timer: NodeJS.Timer | number;

if (typeof window === 'undefined') {
  // Node.js 환경
  timer = setTimeout(() => {
    console.log('Hello, world!');
  }, 1000);
} else {
  // 브라우저 환경
  timer = window.setTimeout(() => {
    console.log('Hello, world!');
  }, 1000);
}
```

참고: https://www.zodaland.com/tip/11

2023-03-07 03:26 UTC, Wilbur0306 commented on components/modal/admin/AdminNotiUserModal.tsx
> +      setModal({ modalName: null });
생각해보니까 논리적으로 말이 안되네요. 수정하도록 하겠습니다.

2023-03-07 07:16 UTC, 42sungwook requested changes
고생하셨습니당. notiUserInfo의 state를 사용하지 않고 있는데 이를 사용하면 post요청 보낼 때 notiUserInfo를 바로 넣어서 쓸 수 있을 것 같아요!

2023-03-07 07:16 UTC, 42sungwook commented on components/modal/admin/AdminNotiUserModal.tsx
> +
이 부분은 만들어놓고 안의 내용들이 다 따로 관리되고 있네요
post 요청할 
intraId는 keywod,
message는 useRef로 관리되고 있고
sendMail은 값을 제대로 참조하지 못하는 걸로 보여요

2023-03-07 07:16 UTC, 42sungwook commented on components/modal/admin/AdminNotiUserModal.tsx
> +        sendMail: true,
sendMail을 무조건 true로 보내는 것 같은데 확인해주세용

2023-03-08 07:46 UTC, Wilbur0306 commented on components/modal/admin/AdminNotiUserModal.tsx
> +
현재 API 명세에서 sendMail이 삭제되었기도 하고 말씀하신 것처럼 useState를 쓰는 의미가 없어서 삭제하였습니다.

2023-03-08 07:46 UTC, Wilbur0306 commented on components/modal/admin/AdminNotiUserModal.tsx
> +        sendMail: true,
API 명세 수정으로 인해 sendMail을 아예 삭제하였습니다.

2023-03-08 07:46 UTC, closed without merging