[GGFE-38] Match
42organization/42gg.client pull request #794
Opened 2023-05-26 07:43 UTC by PHJoon

## 📌 개요 
  - 유저 슬롯 입장 요청 -  api url 변경 + request body 변경
  - 특정 시간대의 경기 매칭 가능 상태 조회 - api url 변경 + response body 변경
  - 게임 종료 요청 -> 삭제됨
  - 매칭 슬롯 취소 - api url 변경
  - 현재 매치 정보 조회 - api url 변경 + response body 변경
 ## 💻 작업사항 

### 유저 슬롯 입장 요청
- api 변경: /pingpong/match/tables{tableId}/{type} -> **/pingpong/match?type={both, rank, normal}**
- request body 변경 사항
`slotId 삭제 => startTime 추가`
- api url에서 type 받는 방식이 대문자로 들어가서 대문자 타입 추가
- 에러코드에 맞는 에러메세지 추가

### 특정 시간대의 경기 매칭 가능 상태 조회
- api 변경 /pingpong/match/tables/{tableId}/{mode}/{type} -> **/pingpong/match/time/scope?mode={mode}**
- response body 변경
```
{
  matchBoards: [{startTime,
    endTime,
    status,
  },...]
}
```
- 리스트 하나로 받게 되면서 matchBoard 수정
- matchSlotList가 안쓰이게 되면서 ui 배치가 이상해짐( 수정필요 )

### 매칭 슬롯 취소
- api 변경: /pingpong/match/slots/{slotId} -> **/pingpong/match?startTime=’yyyy-mm-ddThh:mm’**

### 현재 매치 정보 조회
- api 변경: /pingpong/match/current ⇒ **/pingpong/match**
- response body 변경 사항
`slotId, time 삭제 => startTime, endTime 추가`
- CurrentMatch 타입 변경 -> 경기를 동시에 3개 잡을 수 있게 되면서 배열 형식으로 변경
- CurrentMatch 화면에 나타나는 방식 ( 수정 필요 )
---
추가 작업 필요한 부분
## currentMatch
- 현재 잡은 매치 수에 따라 적용하는 스타일 바뀌어야 -> 슬롯 1개, 2개, 3개 잡은 경우
## MatchBoards
- 매칭 슬롯 모드 both 추가 필요

# 🚫 테스트 필요!
 ## ✅ 변경로직 
  -

2023-05-30 08:20 UTC, yoouyeon reviewed
변경사항 확인했습니다! 👍 (기본적인 매치 과정은 테스트해봤을 때 잘 되는 것 같아요)
나중에 작업한 것들 합치고 나서 이번에 만든 `New*` 타입들 싹 정리하는 과정은 필요할 것 같습니다!!
수고하셨습니다~!

2023-05-30 08:20 UTC, yoouyeon commented on components/match/MatchSlot.tsx
MatchSlot.tsx 파일이랑 MatchSlotList.tsx 파일은 파일내용 전체가 주석처리 되어 있는데 혹시 남겨두신 이유가 있을까요??!
만약에 테스트 후에도 문제 없으면 나중에 헷갈리지 않게 지우는것도 괜찮을 것 같아서요..!

2023-05-30 08:20 UTC, yoouyeon commented on pages/_app.tsx
> +          {/* </ErrorChecker> */}
`<ErrorChecker>` 주석 해제 부탁드립니다 ㅎㅎ

2023-05-30 08:29 UTC, PHJoon commented
주석 수정하고, recoil 난수 추가했습니다!

2023-05-30 09:44 UTC, PHJoon commented
슬롯 headCount 수정하고, new붙은 타입들 수정했습니다!

2023-05-30 13:55 UTC, 42sungwook requested changes
고생하셨습니다! 코멘트 단 내용 읽고 수정 필요한 부분은 수정해주시면 감사하겠습니다 :)

2023-05-30 13:55 UTC, 42sungwook commented on hooks/modal/aftergame/useSubmitModal.ts
이 부분은 pingpong/match/current가 삭제된거면 따로 쓰이는 부분이 있는건가요?
있다면 openStatChangeModal()이랑 완전히 같은 역할을 해서 삭제해도 될거같고
없으면 handler 자체를 지워도 될 것 같아요

2023-05-30 13:55 UTC, 42sungwook commented on hooks/modal/match/useMatchCancelModal.ts
> +      );
slice(0, -3)이 어느 부분을 잘라서 가져온거에요? 가능하면 뭘 나타내는지 알 수 있게 코드를 짜면 더 좋을 것 같아요!

2023-05-30 13:55 UTC, 42sungwook commented on hooks/modal/match/useMatchEnrollModal.ts
>    //type any
이 주석은 이제 지워도 될 것 같아요!

2023-05-30 13:55 UTC, 42sungwook commented on hooks/useSearchBar.ts
> +      // setError('JB06');
searchbar 에러나서 잠깐 주석처리 한 것 같은데 다시 주석 풀어주세요~

2023-05-30 13:55 UTC, 42sungwook commented on styles/match/MatchBoard.module.scss
> +  }
&는 어떤 역할을 하는거에요? 상위 style을 상속받는건가요?

2023-05-30 13:55 UTC, 42sungwook commented on types/modalTypes.ts
> +  startTime: string;
startTime도 시간인것 같은데 Date 타입 대신 string을 쓰신 이유가 있을까요?

2023-05-31 04:13 UTC, PHJoon commented
주석 수정했습니다.
openStatChangeModal 부분도 수정했습니다.

slice(0, -3) 부분은 초 단위까지 데이터를 받아서 초를 빼고 슬라이스 하는 부분입니다.(이에 대해서 일단 해당 api 담당자 분께 초 단위 빼고 보내줄 수 있는지 물어봤습니다)
스타일에서 & 부분은 상위선택자 참조하는 기호여서 여기서는 같은 태그에서 속성 나눠주려고 사용됐습니다.
[https://99geo.tistory.com/5](https://99geo.tistory.com/5)  여기 블로그에 예시가 나와있어서 올려놓을게요.
startTime은 슬롯 시간에 넣을 때 그대로 string 타입을 사용해서 string으로 해놨습니다.

2023-05-31 04:50 UTC, 42sungwook approved these changes
확인했습니다. 고생하셨어요!

2023-05-31 04:50 UTC, merged