[GGFE-54] match time slice 닌자코드 수정
42organization/42gg.client pull request #800
Opened 2023-05-31 06:20 UTC by PHJoon

## 📌 개요 
  - match time 다루는 부분에서 닌자코드 수정
 ## 💻 작업사항 
  - stringToHourMin 함수 추가
  - string의 hour과 min이 string으로 쓰일 때도 있고 number로 쓰일 때도 있어서 반환값은 string, number 둘 다 반환(따로 분리하는 게 나을까요? string만 반환, number만 반환하는 식으로)
 ## ✅ 변경로직 
  -

2023-06-01 04:26 UTC, 42sungwook requested changes
경기가 3개까지 잡혀야하는데 1개만 잡히고 등록된 경기 취소하는 로직에 문제가 있는 것 같아요

2023-06-01 04:26 UTC, 42sungwook commented on hooks/modal/match/useMatchCancelModal.ts
> +      await instance.delete(`/pingpong/match?startTime=${startTime}`);
delete 요청보낼 때 형식이 바뀌어서 그런지 400에러가 나네요ㅠ
메인 브랜치에서는 요청이 잘 되는 것 같은데 확인부탁드려요

2023-06-01 05:29 UTC, 42sungwook approved these changes
변경사항 확인했습니다. 이제 경기가 3개까지 등록 잘되네요 ㅎㅎ

2023-06-01 05:30 UTC, 42sungwook commented on hooks/modal/match/useMatchCancelModal.ts
> +      await instance.delete(`/pingpong/match?startTime=${startTime}`);
슬롯을 다시 누르면 취소되고 위에 라이브 상태에서는 안되는데 이건 다른 이슈에서 고치신다해서 문제가 없었던거네요👍

2023-06-02 03:21 UTC, yoouyeon approved these changes
게임 슬롯 3개 등록하고 3개 취소되는 것 모두 잘 되는 것 확인했습니다~! 👍
string이랑 number 2개 반환하는 건 제가 보기엔 함수를 따로 나누면 헷갈릴 것 같아서 2개 한번에 반환하는 것도 괜찮아 보입니다!!
수고하셨습니다~! 😆

2023-06-02 04:12 UTC, merged