[Fix] [GGFE-42] 0->-1로 변경 togglemode 타입 변경
42organization/42gg.client pull request #805
Opened 2023-06-02 05:07 UTC by parksangmin1543

## 📌 개요 
  - myrank api가 -1로 변경되어 수정, togglemode 타입 변경 
 ## 💻 작업사항 
  - myrank의 시즌에 게임을 한번도 안했다면 주는 값이  0에서 -1로 변경되어 주정했습니다
  - togglemode의 타입을 matchmode로 사용했었는데 toggle특성상 normal, rank두개 만 사용함으로 변경했습니다.
 ## ✅ 변경로직 
  -

2023-06-02 07:49 UTC, PHJoon approved these changes
고생하셨습니다!! 👍  변경사항 확인했습니다!

2023-06-03 01:25 UTC, yoouyeon requested changes
`MatchManualModal`과 `MatchModeWrap`에서도 `useModeToggle`을 사용하고 있는데 여전히 `MatchMode` 타입을 전달하고 있어서 에러가 뜹니다... 다시 확인 부탁드립니다...!

2023-06-03 01:25 UTC, yoouyeon commented on components/mode/modeWraps/RankModeWrap.tsx
> +  setMode: React.Dispatch<React.SetStateAction<'normal' | 'rank'>>;
`MatchMode`처럼 `ToggleMode` 도 여러군데서 쓰이는 타입이라면 `mainType`에 `'NORMAL' | 'RANK'` 이런 식으로 정의하는 것도 괜찮아 보입니당

2023-06-03 02:10 UTC, mike2ox commented on components/mode/modeWraps/RankModeWrap.tsx
> +  setMode: React.Dispatch<React.SetStateAction<'normal' | 'rank'>>;
완전히 같은 값인것으로 보이는데 
```
export type ToggleMode = MatchMode;
```
요렇게 해도 되요

2023-06-04 04:26 UTC, PHJoon commented on components/mode/modeWraps/RankModeWrap.tsx
> +  setMode: React.Dispatch<React.SetStateAction<'normal' | 'rank'>>;
저희  matchMode 라디오 버튼으로 바뀌면 MatchModeWrap과 MatchManualModal에서는 토글모드, useModeToggle을 사용하지 않을 것 같습니다.

2023-06-05 07:28 UTC, parksangmin1543 commented on components/mode/modeWraps/RankModeWrap.tsx
> +  setMode: React.Dispatch<React.SetStateAction<'normal' | 'rank'>>;
matchmode에는 both라는 값이 추가적으로 있어서 타입에러가 발생하는 부분이 있었습니다. 의논 해본 결과 togglemode 타입을 'NORMAL' | 'RANK'로 통일하기로 했습니다.

2023-06-05 12:36 UTC, 42sungwook approved these changes
확인했습니다. 고생하셨어요!

2023-06-08 04:00 UTC, merged