GGFE-44 style rank trophy
42organization/42gg.client pull request #807
Opened 2023-06-02 05:24 UTC by parksangmin1543

## 📌 개요 
  - rank-trophy 메인과 랭킹페이지에 추가
 ## 💻 작업사항 
  - 트로피메인과 랭킹페이지에 따라 높이값 변경
  - 랭킹페이지일때 시즌, 토글 변경시 랭커변경
  - 1,2,3등 순으로 받아오기 때문에 2 1 3등 순으로 변경
 ## ✅ 변경로직 
  -

2023-06-02 08:26 UTC, PHJoon approved these changes
고생하셨습니다!! 👍 에러 주석과 콘솔만 처리하시면 될 것 같아요!!

2023-06-02 08:26 UTC, PHJoon commented on hooks/rank/useRankList.ts
> +      data?.rankList.splice(1, 1);
[data.rankList[0], data.rankList[1]] = [data.rankList[1], data.rankList[0]] 으로도 원하시는 값을 얻을 수 있는 것 같아요!

2023-06-02 09:35 UTC, parksangmin1543 commented on hooks/rank/useRankList.ts
> +      data?.rankList.splice(1, 1);
좋은 방법이네요! 감사합니다

2023-06-04 05:55 UTC, 42sungwook requested changes
고생하셨습니다!

2023-06-04 05:55 UTC, 42sungwook commented on components/rank/topRank/.RankListMain.tsx.swp
이거는 잘못생성된 파일인거같은데 맞을까요?

2023-06-04 05:55 UTC, 42sungwook commented on components/rank/topRank/RankListItemMain.tsx
> +                size={50}
주석은 처리가 덜되어서 남아있는 건가요?
스타일을 찾아보니까 gameResultBig이라는 스타일이 존재하지 않는데 삼항연산을 쓰신 이유가 궁금해요!

2023-06-04 05:55 UTC, 42sungwook commented on components/rank/topRank/RankListMain.tsx
> +  //console.log(rank);
콘솔로그는 지워주세요~

2023-06-04 05:55 UTC, 42sungwook commented on hooks/mode/useModeToggle.ts
> +    setMode(Mode === 'rank' ? 'normal' : 'rank');
이 부분은 다시 소문자로 바뀌는게 맞는건가요?

2023-06-04 05:55 UTC, 42sungwook commented on hooks/useAxiosGet.ts
> +        //setError(err);
주석 풀어주세요!

2023-06-04 05:55 UTC, 42sungwook commented on styles/rank/RankListMain.module.scss
> +}
이쁘게 잘나오네요 짱이에여👍👍

2023-06-04 05:55 UTC, 42sungwook commented on styles/rank/RankListMain.module.scss
> +  grid-template-columns: 1fr 1fr 1fr; /* grid-template-rows로 변경 */
주석으로 남기신 부분들은 확인해주시고 이미 수정된 사항이면 지워주시면 감사하겠습니다~

2023-06-04 05:55 UTC, 42sungwook commented on styles/rank/RankListMain.module.scss
> +  //text-shadow: $text-border-black;
주석22

2023-06-04 05:55 UTC, 42sungwook commented on utils/infinityScroll.ts
> +      //else setError('KP01');
여기도 주석 해제해주세요

2023-06-04 08:25 UTC, PHJoon commented on components/rank/topRank/RankListItemMain.tsx
> +                size={50}
gameResultBig은 PlayerImage에서 기존에 game결과 보여줄 때 크게 보이는 항목의 사진에 사용하는 스타일으로 알고 있어요! (원래 있던 것이라 변경사항에는 반영되지 않았네요)

2023-06-07 08:06 UTC, parksangmin1543 commented on components/rank/topRank/RankListItemMain.tsx
> +                size={50}
gameResultBig은 원래 사용되던 부분이고 ranktropy는 rank가 1등인 경우에만 크기변화가 필요해서 따로 준 부분입니다.

2023-06-13 08:53 UTC, PHJoon requested changes
랭크 트로피 이미지 예쁘게 잘 적용됩니다 👍 코멘트에 남겨놨는데 랭크 트로피에서 intraId 폰트 색상 다른 거랑 뱅 이미지 모바일에서 움직이는 거만 수정하시면 될 듯합니다!! 고생하셨습니다!! 👍

2023-06-13 08:53 UTC, PHJoon commented on components/rank/RankList.tsx
> +export default function RankList(prop: RankListProps) {
이 부분은 {toggleMode, season, isMain}: RankListProps로 인자 안에서 구조분해해도 될 것 같아요!

2023-06-13 08:53 UTC, PHJoon commented on components/rank/RankList.tsx
> +              user={makeUser(item)}
makeUser의 반환값도 타입 지정해주면 RankListItem에서 타입 경고 없어질 듯 합니다!

2023-06-13 08:53 UTC, PHJoon commented on components/rank/topRank/RankListItemMain.tsx
> +              <span>{intraId}</span>
피그마 보시면 intraId도 순위에 따라 폰트색깔이 달라지는 것 같아요!!

2023-06-13 08:53 UTC, PHJoon commented on components/rank/topRank/RankListMain.tsx
> +  const bangElements = Array.from({ length: 5 }, (_, index) => (
Array를 이렇게도 만들 수 있군요. 배워갑니다!! 👍

2023-06-13 08:53 UTC, PHJoon commented on styles/PlayerImage.module.scss
> +@media (max-width: 767px) {
미디어쿼리로 화면 크기에 따라 크기 다르게 적용하는 거 좋네요! 👍

2023-06-13 08:53 UTC, PHJoon commented on styles/rank/RankListMain.module.scss
> +.mainData:nth-child(1) {
nth-child 활용하는 거 배우고 갑니다!! 👍

2023-06-13 08:53 UTC, PHJoon commented on styles/PlayerImage.module.scss
> +.ranktropybig {
플레이어 이미지가 피그마에서는 테두리가 없는데 따로 추가하신 걸까요?

2023-06-13 08:53 UTC, PHJoon commented on styles/rank/RankListMain.module.scss
> +.bang {
모바일 화면에서는 bang이 한쪽으로 쏠려서 나오네요 😱 수정부탁드려요!

2023-06-13 09:55 UTC, yoouyeon reviewed
CSS 마스터,,,😳  트로피 부분 예쁘게 잘 나오고 에러들도 사라졌네요!! 👍 수고하셨습니다!!

2023-06-13 09:55 UTC, yoouyeon commented on styles/PlayerImage.module.scss
> +}
너비에 따라 크기 다르게 하니까 확실히 덜 어색한 것 같네요 👍

2023-06-13 09:55 UTC, yoouyeon commented on styles/rank/RankList.module.scss
> +  margin-top: -4rem;
margin에 음수값을 주신 이유가 무엇인가요???

2023-06-13 09:55 UTC, yoouyeon commented on styles/rank/RankList.module.scss
> +  }
`pointer-events: auto` 는 여기서 어떤 기능을 하는건가요..?
그리고 `myRank-text` 를 검색해봤을 때 이 클래스로 지정된 클래스가 없는 것 같은데 어디서 쓰이는건가요?

2023-06-13 09:55 UTC, yoouyeon commented on styles/rank/RankListMain.module.scss
> +  background-clip: text;
`background-clip` 속성으로 text에만 배경을 적용할 수 있는건가요?? 처음 알았네요 👍

2023-06-13 09:55 UTC, yoouyeon commented on styles/rank/RankListMain.module.scss
> +.rankNumber2 {
언뜻 봤을 때 `rankNumber1, 2, 3`들에 비슷한 속성들이 많아 보이는데 가능하면 mixin으로 합치는 것도 보기에 좋을 것 같아요

2023-06-15 06:44 UTC, parksangmin1543 commented on components/rank/RankList.tsx
> +          ))}
배열이 부분적으로 없을경우 , 아예없을경우 물음표나오게 처리했습니다. 스토리는 1,2,3등 데이터없을때 에러가 떠서 3등만 없을경우만 확인했습니다.

2023-06-15 06:45 UTC, parksangmin1543 commented on components/rank/RankListItem.tsx
>      topStandard: rank < 4 ? styles.top : styles.standard,
ranklist 데이터를 전에는 가입한 모든 분들을 받아와 한번도 안했을경우에도 랭킹에 '-'이렇게 표시하기 위해서 사용했었습니다. 현재는 필요없어서 수정했습니다.

2023-06-15 06:46 UTC, parksangmin1543 commented on components/rank/topRank/RankListItemMain.tsx
> +            } ${toggleMode === 'NORMAL' && styles.normal}`}
좋은 방법 감사합니다!

2023-06-15 06:46 UTC, parksangmin1543 commented on styles/PlayerImage.module.scss
> +}
감사합니다!

2023-06-15 06:47 UTC, parksangmin1543 commented on styles/rank/RankList.module.scss
> +  margin-top: -4rem;
노티바와 타이틀사이가 멀어서 추가했었는데 통일감을 위해 일단 삭제했습니다. 다른 좋은 방법 생각해보면 좋을것 같아요

2023-06-15 06:48 UTC, parksangmin1543 commented on styles/rank/RankListMain.module.scss
> +  background-clip: text;
당근 감사합니다!

2023-06-15 06:49 UTC, parksangmin1543 commented on styles/rank/RankListMain.module.scss
> +.rankNumber2 {
mixin을 활용해서 수정했습니다.

2023-06-15 08:41 UTC, merged