[GGFE-46] Game Result List 스타일
42organization/42gg.client pull request #814
Opened 2023-06-05 05:12 UTC by yoouyeon

## 📌 개요 
  - 게임 목록 스타일을 적용했습니다.
 ## 💻 작업사항 
  - 기본적인 Item 디자인 변경
  - 기존의 Normal / Rank 게임에 따라 배경색이 달랐던 부분을 삭제하고 인덱스에 따라 밝은 배경과 어두운 배경이 번갈아 나올 수 있도록 변경
  - BigItem에 `z-index 1` 을 설정하면서 가려지는 match button의 z-index 값 변경
  - main page의 section title을 디자인에 맞게 수정, title을 props로 받아올 수 있게 함.
  - game page 디자인 중 radio 버튼과 더보기 버튼 스타일 변경 (아직 디자인이 완성된 것 같지 않아 보여서 이후 변경될 가능성도 있을 것 같습니다...)
  - 불필요하게 div 태그로 감싼 부분을 삭제하거나, 빈 태그로 변경

단위를 px로 지정했을 때 figma에서 보이는 디자인과 실제 구현된 디자인이 좀 달라 보여서 모든 길이 단위를 16px = 1rem을 기준으로 하는 rem으로 변경해서 지정해두었는데 괜찮은 방법인지 모르겠습니다.... 🤔

**❗️ BigItem의 Wait과 Live 상태일때의 디자인은 아직 만들어지지 않아서 기존 디자인 그대로입니다.**

 ## ✅ 변경로직 
  -

2023-06-05 08:33 UTC, parksangmin1543 approved these changes
메인ranking 더보기디자인 변경된 것 확인했습니다.

2023-06-05 09:58 UTC, PHJoon requested changes
고생하셨습니다! 게임 스타일 예쁘게 잘 적용된 것 확인했습니다! 👍
game 페이지에서 유저 검색하는 dropdown이 게임아이템에 가려지는 것만 해결하시면 될 것 같습니다!

2023-06-05 09:58 UTC, PHJoon commented on styles/PlayerImage.module.scss
> +    @include gameResultImage(2.734rem);
(개인의견입니다) 기존에 비해 사람 얼굴이 많이 작아진 것 같은데 조금 더 키워도 되지 않을까요??

2023-06-05 12:05 UTC, yoouyeon commented on styles/PlayerImage.module.scss
> +    @include gameResultImage(2.734rem);
figma의 px을 그대로 rem으로 변환해서 사용한거긴 한데, 지금 보니까 figma에서도 원래의 디자인에 비해서는 사진이 좀 작긴 하네요 ㅎㅎ 다른 분들 의견도 궁금합니닷

2023-06-05 12:29 UTC, yoouyeon commented
z-index 수정하는데 시간이 좀 걸릴 것 같아서 일단 PR 닫아두겠습니다 🫠

2023-06-07 09:44 UTC, parksangmin1543 commented on styles/PlayerImage.module.scss
> +    @include gameResultImage(2.734rem);
제가 2등3등에서 gameresultbig를 활용하고 있었는데 제가 수정하겠습니다

2023-06-08 04:40 UTC, 42sungwook approved these changes
전체적으로 불필요한 div태그는 없애주셔서 보기 더 편해졌네요 고생하셨습니다👍

2023-06-08 04:40 UTC, 42sungwook commented on components/game/GameResultList.tsx
> +            <React.Fragment key={pageIndex}>
React.Fragment가 `<> </>`요걸 지칭하는걸로 알고 있는데 키값을 쓸 수 있는건 처음알았네요👍

2023-06-08 04:40 UTC, 42sungwook commented on pages/index.tsx
> +        <Section path='rank' sectionTitle={'Ranking'} />
제목도 같이 합치신거네요👍

2023-06-08 05:40 UTC, yoouyeon commented on components/game/GameResultList.tsx
> +            <React.Fragment key={pageIndex}>
`div` 태그를 지우고 빈 태그를 쓰고 싶었는데, `<> </>` 에는 직접 키값을 넣지 못하더라구요..ㅎㅎ `React.Fragment`에는 키값을 쓸 수 있길래 이걸로 써 줬습니다 😁

2023-06-08 05:44 UTC, yoouyeon commented
`/game` 페이지 목록 디자인이 단순히 색깔만 바뀌는게 아니라 z-index 설정했던 부분도 다시 수정해줘야 할 것 같아서 다시... PR 닫고 수정해서 열게요!!

2023-06-13 06:45 UTC, yoouyeon commented
새로 추가된 디자인들 적용해서 다시 PR 열겠습니다! (새로 추가된 내용들은 위에 정리해둘게요)

2023-06-13 07:16 UTC, mike2ox reviewed
😃

2023-06-13 07:16 UTC, mike2ox commented on components/game/big/GameResultBigScore.tsx
> +      {makeScoreStatus(status, time, radioMode)}
컴포넌트 형식으로 바꿔보시는건 어떨까요
해당 함수 방식이 () => JSX.element라서 가능해 보이거든요

2023-06-13 07:16 UTC, mike2ox commented on components/main/Section.tsx
>  };
type pathType = Record<string, JSX.Element>;

2023-06-13 07:16 UTC, mike2ox commented on components/mode/modeItems/UserGameSearchBar.tsx
> +        {keyword && (
참고 : https://bit.ly/42Bc7qw

2023-06-13 07:25 UTC, yoouyeon commented on components/mode/modeItems/UserGameSearchBar.tsx
> +        {keyword && (
오오 위에 쓴 삼항연산자는 둘다 boolean이라서 괜찮지만 이건 삼항연산자로 수정해주는게 좋겠네요...! 감사합니당

2023-06-13 08:05 UTC, parksangmin1543 approved these changes
모바일 환경에서도 잘되는것 확인했습니다. tag를 많이 줄여주셔서 보기 더 편했던것 같아요

2023-06-13 08:16 UTC, PHJoon requested changes
스타일 예쁘게 잘 적용된 거 확인했습니다!! 코멘트에 남겼는데 게임페이지에서 검색창이 검색할 때 크기가 변하고 x표시 너무 작은 것은 수정이 필요할 것 같습니다!! 고생하셨습니다! 👍

2023-06-13 08:16 UTC, PHJoon commented on components/mode/modeItems/UserGameSearchBar.tsx
검색하면 검색창 크기가 변하고 x표시가 작게 보이는 것 같아요!

2023-06-13 08:16 UTC, PHJoon commented on stories/game/GameResultBigItem.stories.tsx
스토리별로 컴포넌트 확인할 수 있는 거 정말 좋습니다!! live, wait, end 다 잘 되네요! 👍

2023-06-13 08:16 UTC, PHJoon commented on styles/game/GameResultItem.module.scss
> +  @if ($type == 'SMALL') {
믹스인에서 조건문 써서 나눠주는 방법도 있군요. 배워갑니다! 👍

2023-06-13 08:24 UTC, yoouyeon commented on components/mode/modeItems/UserGameSearchBar.tsx
뒤의 X 버튼을 `keyword`가 있는 경우에만 보여주게 했었는데 이렇게 하니까 X 버튼이 없는 경우에 검색창 크기가 줄어드는 것이었습니다... 조건부 랜더링 하는 부분을 삭제하고 `visibility` 속성을 `visible`이랑 `hidden`으로 넣어주는 방식으로 변경했어요!

2023-06-13 08:40 UTC, yoouyeon commented on components/main/Section.tsx
>  };
오... Record type은 처음 봤는데 Index Signature랑 동일한거네요...!

2023-06-13 09:58 UTC, mike2ox commented on components/game/big/GameResultBigScore.tsx
> +function ScoreStatus({ status, time, radioMode }: scoreStatusProps) {
👍

2023-06-15 05:51 UTC, merged