[Chore] Css order 수정
42organization/42gg.client pull request #890
Opened 2023-06-26 09:43 UTC by PHJoon

## 📌 개요 
  - Css order 수정
 ## 💻 작업사항 
  - github wiki의 css order에 맞게 수정했습니다.
 ## ✅ 변경로직 
  -

2023-06-26 09:58 UTC, yoouyeon requested changes
확인했습니다!! 수고하셨어용 😵‍💫👍

2023-06-26 09:58 UTC, yoouyeon commented on styles/Layout/CurrentMatchInfo.module.scss
> -  font-size: 0.75rem;
이거는 일부러 삭제하신건가요???

2023-06-27 00:20 UTC, PHJoon commented on styles/Layout/CurrentMatchInfo.module.scss
> -  font-size: 0.75rem;
제가 중복해서 적은 부분이라 하나는 삭제했습니다 아래 더보기로 보면 하나 더 있어요👍

2023-06-27 02:33 UTC, 42sungwook approved these changes
고생하셨습니다👍

2023-06-27 18:33 UTC, yoouyeon approved these changes

2023-06-28 03:55 UTC, parksangmin1543 approved these changes
수고많으셨습니다!

2023-06-28 08:29 UTC, merged