[GGFE-172] 상점 매뉴얼 모달
42organization/42gg.client pull request #920
Opened 2023-08-10 06:44 UTC by hyobb109

## 📌 개요 
  - 상점 매뉴얼 모달
 ## 💻 작업사항 
  - 상점 페이지 매뉴얼 버튼 클릭 시 매뉴얼 모달을 띄웁니다
  - 코인 정책 탭에서 코인 획득, 사용, 내역 확인 방법을 설명합니다
  - 상점 이용 탭에서 아이템 구매, 선물 및 사용 방법 등을 설명합니다 
  - 기존 매치 매뉴얼 모달 contentType의 description을 string[]에서 descriptionType[] 로 수정하여 들여쓰기가 가능하도록 수정했습니다 
  - 매뉴얼의 상세한 내용은 추후 수정 필요할 것 같습니다

2023-08-10 09:13 UTC, PHJoon approved these changes
매뉴얼 모달 잘 뜨고 라디오 버튼도 잘 됩니다! 설명까지 꼼꼼히 다 채우셨네요. 😲 중첩 리스트 실제 적용된 건 처음 보는데 잘 적용된 것 같아요! 고생하셨습니다!! 👍👍

2023-08-10 09:13 UTC, PHJoon commented on components/modal/store/StoreManualModal.tsx
> +          content: ['- 하루 한 번 로그인 시 출석하기 버튼만 눌러도 1코인 획득'],
content 마다 앞에 '- '붙이신 건 css list-style에 '- '와 같은 형식이 없어서 그러신 걸까요?

2023-08-10 09:13 UTC, PHJoon commented on types/modalTypes.ts
> +// 지워도 되는 것?
아마 처음에는 Manual하고 manual이 조금 다른 타입이었던거 같은데 작업하다보니 두개가 동일하게 정의된거 같네요. 
Manual 타입이 MatchManualModal에서 쓰이고 있어서 그 부분을 manual 로 바꾸고 지우시면 될거 같아요. 👍

2023-08-10 12:55 UTC, yoouyeon commented on components/modal/store/StoreManualModal.tsx
> +          content: ['- 하루 한 번 로그인 시 출석하기 버튼만 눌러도 1코인 획득'],
요거는 list-style-type 속성으로 커스텀 할 수 있어요! https://developer.mozilla.org/en-US/docs/Web/CSS/list-style-type

2023-08-10 13:02 UTC, yoouyeon commented on components/modal/store/StoreManualModal.tsx
> +                )}
여기 `e`라는 변수 이름을 `item`의 element라는 의미로 지어주신 것 같은데 `e`라고 적혀있으니까 개인적으로는 event나 event를 의미하는 변수명으로 `e`를 자주 쓰다 보니까 의미가 한눈에 잘 안들어오게 되는 것 같습니다..ㅜㅜ
좀 더 "설명" 과 어울리는 변수명으로 지어주면 좋을 것 같아요!

2023-08-10 13:13 UTC, yoouyeon commented on components/mode/modeItems/RadioBoxWrapper.tsx
> +      }
오 저였다면 `||` 연산자로 계속 조건을 이어붙였을 것 같은데 `includes`로 'STORE' 문자열이 있는지 확인해주는 방법이 확장성 측면에서도 그렇고 더 깔끔하기도 하고 좋네여 👍
만약에 'STORE' 라는 prefix가 있는 조건을 생각하고 계셨던거라면 `startsWith` 메서드로 'STORE' 문자열로 시작하는지 확인해주는 방법도 뭔가 의도치 않은 결과를 내지 않기에 좋을 것 같아요! https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

2023-08-10 16:03 UTC, hyobb109 commented on components/modal/store/StoreManualModal.tsx
> +          content: ['- 하루 한 번 로그인 시 출석하기 버튼만 눌러도 1코인 획득'],
오 스트링으로도 지정이 되네요! 수정하겠습니당

2023-08-10 16:12 UTC, hyobb109 commented on components/modal/store/StoreManualModal.tsx
> +                )}
기존 것 그냥 가져다 쓰면서 변수명까지는 생각 못했네요!ㅎㅎ classname이랑 맞춰서 rule로 수정했습니다!

2023-08-10 16:14 UTC, hyobb109 commented on components/mode/modeItems/RadioBoxWrapper.tsx
> +      }
오 딱 그걸 원했던 건데 startsWith이 있었네요!!! 링크까지 첨부해주시다니 감사합니다 ㅎㅎ 많이 배워가요!!

2023-08-11 05:43 UTC, yoouyeon requested changes
`Manual` 타입을 `MatchManualModal` 컴포넌트에서 사용하고 있어서 import 에러가 뜨네요..! 
`MatchManualModal`에서 사용하는 타입도 `manual` 로 바꿔주면 될 것 같습니다!

2023-08-11 06:16 UTC, hyobb109 commented
타입명 일관성 있게 대문자로 두는게 좋을 것 같아서 MatchManualModal은 그대로 두고 ModalTypes에서 manual을 Manual로 수정하였습니다! 제꺼에서는 오류가 안나서 몰랐네요ㅠ

2023-08-11 06:27 UTC, yoouyeon approved these changes
확인했습니다!! 수고하셨습니다~!! 😆👍

2023-08-11 06:46 UTC, merged